-- Batches not send to CBO
SELECT 	COUNT(*) 
FROM 	DCO_TXN_INFO 
WHERE 	STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT';

SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		DCO_TXN_INFO.CBO_GRP_STATUS AS "CBO Group Status",
		DCO_TXN_INFO.STATUS  AS "Status",
		DCO_TXN_INFO.DESCRIPTION AS "Description",
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE 	DCO_TXN_INFO.STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT';

-- Resend Pending Batches
UPDATE DCO_TXN_INFO 
SET DCO_TXN_INFO.STATUS = 'DCO_SEND_TO_CBO_PT' 
WHERE DCO_TXN_INFO.STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT' AND DCO_TXN_INFO.CBO_GRP_STATUS = 'RJCT 1001'

UPDATE DCO_TXN_INFO 
SET DCO_TXN_INFO.STATUS = 'DCO_SEND_TO_CBO_PT' 
WHERE DCO_TXN_INFO.STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT'

--------------------------------------------------------
--DCO Accepted Transaction
SELECT 	COUNT(*), SUM(DCO_TXN_INFO.AMOUNT)
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171129T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171130T12:00:00.000' AND
		DCO_TXN_INFO.CBO_TXN_STATUS NOT LIKE 'RJCT%'
		
SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.STATUS, DCO_TXN_INFO.STATUS)  AS "Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.DESCRIPTION, DCO_TXN_INFO.DESCRIPTION) AS "Description",
		coalesce(CANO_REVO_RETO_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE || '-' || CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "Cancelation Error", 
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
LEFT	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171126T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171127T12:00:00.000' AND
		DCO_TXN_INFO.CBO_TXN_STATUS NOT LIKE 'RJCT%'
ORDER BY DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP ASC, 
		 DCO_GROUP_HEADER_INFO.CHANNEL ASC,
		 DCO_GROUP_HEADER_INFO.BATCH_REFERENCE ASC,
		 DCO_TXN_INFO.TXN_REF ASC

------------------------------------------------------------
--DCO Rejected Transaction By CBO
SELECT 	COUNT(*), SUM(DCO_TXN_INFO.AMOUNT)
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171206T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171207T12:00:00.000' AND
		DCO_TXN_INFO.CBO_TXN_STATUS LIKE 'RJCT%'

SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		DCO_TXN_INFO.STATUS  AS "Original Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.STATUS, '-')  AS "Cancel Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.DESCRIPTION, DCO_TXN_INFO.DESCRIPTION) AS "Description",
		coalesce(CANO_REVO_RETO_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE || '-' || CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "Cancelation Error", 
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
LEFT	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171206T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171207T12:00:00.000' AND
		DCO_TXN_INFO.CBO_TXN_STATUS LIKE 'RJCT%'
ORDER BY DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP ASC, 
		 DCO_GROUP_HEADER_INFO.CHANNEL ASC,
		 DCO_GROUP_HEADER_INFO.BATCH_REFERENCE ASC,
		 DCO_TXN_INFO.TXN_REF ASC

------------------------------------------------------------
--DCO Cancelled Transaction By OAB
SELECT 	COUNT(*), SUM(DCO_TXN_INFO.AMOUNT)
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
INNER	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171127T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171128T12:00:00.000' 

SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		CANO_REVO_RETO_TXN_INFO.STATUS AS "Status",
		CANO_REVO_RETO_TXN_INFO.DESCRIPTION AS "Description",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "CBS Fault String",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE AS "CBS Fault Code",
		coalesce(CANO_REVO_RETO_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE || '-' || CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "Cancelation Error", 
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
INNER	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171129T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171130T12:00:00.000' 
ORDER BY DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP ASC, 
		 DCO_GROUP_HEADER_INFO.CHANNEL ASC,
		 DCO_GROUP_HEADER_INFO.BATCH_REFERENCE ASC,
		 DCO_TXN_INFO.TXN_REF ASC

---------------------------------------------------------------------------------
---------------------------------------------------------------------------------
-- DCI Accepted Transaction 
SELECT 	COUNT(*), SUM(DCI_TXN_INFO.INTERBANK_SETTLE_AMT)
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-12-07 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_SUCCESS'
		 
SELECT 	DCI_GP_HEADER_INFO.CREATION_DATETIME AS "Transaction Timestamp",
		DCI_GP_HEADER_INFO.INST_AGT_FIN_ID_BICFI AS "Sender Bank",
		DCI_GP_HEADER_INFO.MSG_ID AS "CBO Batch Reference",
		DCI_TXN_INFO.PMT_ID_TXN_ID AS "CBO Transaction Reference",
		DCI_TXN_INFO.STATUS AS "Status",
		DCI_TXN_INFO.DESCRIPTION AS "Description",
		DCI_TXN_INFO.CBS_PAY_REF AS "Posting Reference",
		DCI_TXN_INFO.FAULT_CODE || '-' || DCI_TXN_INFO.FAULT_STRING AS "Posting Error",
		DCI_TXN_INFO.INTERBANK_SETTLE_AMT AS "Amount",
		DCI_TXN_INFO.CDTR_ACCT_OTHR_ID AS "Beneficiary Account",
		DCI_TXN_INFO.CDTR_NAME AS "Beneficiary Name",
		DCI_GP_HEADER_INFO.PMT_TP_INF_CTGY_PURP_PRTRY AS "Batch Purpose",
		DCI_TXN_INFO.PURP_PROPTYCHAR AS "Transaction Purpose",
		DCI_TXN_INFO.DBTR_ACCT_OTHR_ID AS "Ordering Customer Account",
		DCI_TXN_INFO.DBTR_NAME AS "Oedering Customer Name"
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-30 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_SUCCESS'
ORDER BY DCI_GP_HEADER_INFO.CREATION_DATETIME DESC


SELECT 	DCI_GP_HEADER_INFO.CREATION_DATETIME AS "Transaction Timestamp",
		DCI_GP_HEADER_INFO.INST_AGT_FIN_ID_BICFI AS "Sender Bank",
		DCI_GP_HEADER_INFO.MSG_ID AS "CBO Batch Reference",
		DCI_TXN_INFO.PMT_ID_TXN_ID AS "CBO Transaction Reference",
		DCI_TXN_INFO.STATUS AS "Status",
		DCI_TXN_INFO.DESCRIPTION AS "Description",
		DCI_TXN_INFO.CBS_PAY_REF AS "Posting Reference",
		DCI_TXN_INFO.FAULT_CODE || '-' || DCI_TXN_INFO.FAULT_STRING AS "Posting Error",
		DCI_TXN_INFO.INTERBANK_SETTLE_AMT AS "Amount",
		DCI_TXN_INFO.CDTR_ACCT_OTHR_ID AS "Beneficiary Account",
		DCI_TXN_INFO.CDTR_NAME AS "Beneficiary Name",
		DCI_GP_HEADER_INFO.PMT_TP_INF_CTGY_PURP_PRTRY AS "Batch Purpose",
		DCI_TXN_INFO.PURP_PROPTYCHAR AS "Transaction Purpose",
		DCI_TXN_INFO.DBTR_ACCT_OTHR_ID AS "Ordering Customer Account",
		DCI_TXN_INFO.DBTR_NAME AS "Oedering Customer Name"
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-30 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_FAILED'
ORDER BY DCI_GP_HEADER_INFO.CREATION_DATETIME DESC


SELECT COUNT(*),SUM(DCI_TXN_INFO.INTERBANK_SETTLE_AMT) FROM 
DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-29 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_SUCCESS'
ORDER BY DCI_GP_HEADER_INFO.CREATION_DATETIME DESC



SELECT COUNT(*),SUM(DCI_TXN_INFO.INTERBANK_SETTLE_AMT) FROM 
DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-29 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_FAILED'
ORDER BY DCI_GP_HEADER_INFO.CREATION_DATETIME DESC	

------------------------------------------
--DCI Rejected Transaction
SELECT 	COUNT(*), SUM(DCI_TXN_INFO.INTERBANK_SETTLE_AMT)
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-28 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_FAILED'
		
SELECT 	DCI_GP_HEADER_INFO.CREATION_DATETIME AS "Transaction Timestamp",
		DCI_GP_HEADER_INFO.INST_AGT_FIN_ID_BICFI AS "Sender Bank",
		DCI_GP_HEADER_INFO.MSG_ID AS "CBO Batch Reference",
		DCI_TXN_INFO.PMT_ID_TXN_ID AS "CBO Transaction Reference",
		DCI_TXN_INFO.STATUS AS "Status",
		DCI_TXN_INFO.DESCRIPTION AS "Description",
		DCI_TXN_INFO.FAULT_CODE || '-' || DCI_TXN_INFO.FAULT_STRING AS "Posting Error",
		DCI_TXN_INFO.INTERBANK_SETTLE_AMT AS "Amount",
		DCI_TXN_INFO.CDTR_ACCT_OTHR_ID AS "Beneficiary Account",
		DCI_TXN_INFO.CDTR_NAME AS "Beneficiary Name",
		DCI_GP_HEADER_INFO.PMT_TP_INF_CTGY_PURP_PRTRY AS "Batch Purpose",
		DCI_TXN_INFO.PURP_PROPTYCHAR AS "Transaction Purpose",
		DCI_TXN_INFO.DBTR_ACCT_OTHR_ID AS "Ordering Customer Account",
		DCI_TXN_INFO.DBTR_NAME AS "Oedering Customer Name"
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-12-07 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_FAILED'

--------------------------------
-- DCI Cancelled Transaction
SELECT 	COUNT(*), SUM(DCI_TXN_INFO.INTERBANK_SETTLE_AMT)
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
INNER	JOIN CANI_TXN_INFO
		ON CANI_TXN_INFO.ORGNL_TX_ID=DCI_TXN_INFO.PMT_ID_TXN_ID		
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-28 00:00:00', 'yyyy-mm-dd hh24-mi-ss')
		
SELECT 	DCI_GP_HEADER_INFO.CREATION_DATETIME AS "Transaction Timestamp",
		DCI_GP_HEADER_INFO.INST_AGT_FIN_ID_BICFI AS "Sender Bank",
		DCI_GP_HEADER_INFO.MSG_ID AS "CBO Batch Reference",
		DCI_TXN_INFO.PMT_ID_TXN_ID AS "CBO Transaction Reference",
		coalesce(CANI_TXN_INFO.STATUS, DCI_TXN_INFO.STATUS)  AS "Status",
		coalesce(CANI_TXN_INFO.DESCRIPTION, DCI_TXN_INFO.DESCRIPTION) AS "Description",
		DCI_TXN_INFO.CBS_PAY_REF AS "Posting Reference",
		DCI_TXN_INFO.FAULT_CODE || '-' || DCI_TXN_INFO.FAULT_STRING AS "Posting Error",
		coalesce(CANI_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANI_TXN_INFO.FAULT_CODE || '-' || CANI_TXN_INFO.FAULT_STRING AS "Cancelation Error", 
		DCI_TXN_INFO.INTERBANK_SETTLE_AMT AS "Amount",
		DCI_TXN_INFO.CDTR_ACCT_OTHR_ID AS "Beneficiary Account",
		DCI_TXN_INFO.CDTR_NAME AS "Beneficiary Name",
		DCI_GP_HEADER_INFO.PMT_TP_INF_CTGY_PURP_PRTRY AS "Batch Purpose",
		DCI_TXN_INFO.PURP_PROPTYCHAR AS "Transaction Purpose",
		DCI_TXN_INFO.DBTR_ACCT_OTHR_ID AS "Ordering Customer Account",
		DCI_TXN_INFO.DBTR_NAME AS "Oedering Customer Name"
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
INNER	JOIN CANI_TXN_INFO
		ON CANI_TXN_INFO.ORGNL_TX_ID=DCI_TXN_INFO.PMT_ID_TXN_ID		
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-23 00:00:00', 'yyyy-mm-dd hh24-mi-ss')
		
------------------------------------------------------------

SELECT  DCI_GP_HEADER_INFO.CREATION_DATETIME AS "Transaction Timestamp",
		DCI_GP_HEADER_INFO.INST_AGT_FIN_ID_BICFI AS "Sender Bank",
		DCI_GP_HEADER_INFO.MSG_ID AS "CBO Batch Reference",
		DCI_TXN_INFO.PMT_ID_TXN_ID AS "CBO Transaction Reference",
		DCI_TXN_INFO.STATUS AS "Status",
		DCI_TXN_INFO.DESCRIPTION AS "Description",
		DCI_TXN_INFO.FAULT_CODE || '-' || DCI_TXN_INFO.FAULT_STRING AS "Posting Error",
		DCI_TXN_INFO.INTERBANK_SETTLE_AMT AS "Amount",
		DCI_TXN_INFO.CDTR_ACCT_OTHR_ID AS "Beneficiary Account",
		DCI_TXN_INFO.CDTR_NAME AS "Beneficiary Name",
		DCI_GP_HEADER_INFO.PMT_TP_INF_CTGY_PURP_PRTRY AS "Batch Purpose",
		DCI_TXN_INFO.PURP_PROPTYCHAR AS "Transaction Purpose",
		DCI_TXN_INFO.DBTR_ACCT_OTHR_ID AS "Ordering Customer Account",
		DCI_TXN_INFO.DBTR_NAME AS "Oedering Customer Name"
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-28 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.PMT_ID_TXN_ID IN ('BMCT0IA116915001',
									'BMCT0IA121284001',
									'SCBL0IC001740001',
									'BMCT0IA126234001')
									
									
																		
select * from DCI_TXN_INFO where PMT_ID_TXN_ID  LIKE 'NBOM0IFHYEF3R%'
		
ALTER TABLE DCI_TXN_INFO MODIFY CBS_TRAN_REF VARCHAR2(100)
ALTER TABLE DCI_TXN_INFO MODIFY FAULT_STRING VARCHAR2(1000)

		
UPDATE DCO_TXN_INFO
SET BENEF_BANK = 'NBOMOMRX', DCO_TXN_INFO.STATUS = 'DCO_SEND_TO_CBO_PT'   
WHERE 	BENEF_BANK = 'NBOMORX'


select * from DCO_GROUP_HEADER_INFO WHERE Channel = 'SO'

ALTER TABLE DCI_TXN_INFO MODIFY DESCRIPTION VARCHAR2(500)

ALTER TABLE DCO_TXN_INFO MODIFY FAULT_STRING VARCHAR2(1000)

ALTER TABLE DCO_TXN_INFO MODIFY CBS_TRAN_REF VARCHAR2(100)

ALTER TABLE CANI_TXN_INFO MODIFY FAULT_STRING VARCHAR2(1000)

ALTER TABLE CANI_TXN_INFO MODIFY CBS_TRAN_REF VARCHAR2(100)

ALTER TABLE CANO_REVO_RETO_TXN_INFO MODIFY FAULT_STRING VARCHAR2(1000)

ALTER TABLE CANO_REVO_RETO_TXN_INFO MODIFY CBS_TRAN_REF VARCHAR2(100)

ALTER TABLE PRI_TXN_INFO MODIFY FAULT_STRING VARCHAR2(1000)


ALTER TABLE PRI_TXN_INFO MODIFY CBS_TRAN_REF VARCHAR2(100)

ALTER TABLE REVI_TXN_INFO MODIFY FAULT_STRING VARCHAR2(1000)

ALTER TABLE REVI_TXN_INFO MODIFY CBS_TRAN_REF VARCHAR2(100)

ALTER TABLE WPS_SIF_RECORD_INFO MODIFY CBS_FAULT_STRING VARCHAR2(1000)

ALTER TABLE WPS_SIF_HEADER_INFO MODIFY CBS_FAULT_STRING VARCHAR2(1000)




SELECT 	*
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE 	DCO_TXN_INFO.STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT';

SELECT * FROM  DCO_TXN_INFO 
WHERE DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK IN ('4975', '5660', '5664', '5601') AND DCO_TXN_INFO.STATUS = 'CANCEL_INITIATED'

UPDATE DCO_TXN_INFO SET STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT'
WHERE DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK IN ('4975', '5660', '5664', '5601') AND DCO_TXN_INFO.STATUS = 'CANCEL_INITIATED'

SELECT * FROM PAYLOAD_LOGGING_TAB WHERE MESSAGE_ID LIKE 'OMAB1IW890204' 

SELECT * FROM DCI_TXN_INFO WHERE MSG_ID = 'BMCT0IA00%';

DELETE FROM CANO_REVO_RETO_TXN_INFO WHERE GRP_HDR_ID_TXN_INFO_FK = '2062'
DELETE FROM CANO_REVO_RETO_GRPHDR_INFO WHERE GRP_HEADER_ID = '2062'






SELECT 	DCI_GP_HEADER_INFO.CREATION_DATETIME AS "Transaction Timestamp",
		DCI_GP_HEADER_INFO.INST_AGT_FIN_ID_BICFI AS "Sender Bank",
		DCI_GP_HEADER_INFO.MSG_ID AS "CBO Batch Reference",
		DCI_TXN_INFO.PMT_ID_TXN_ID AS "CBO Transaction Reference",
		DCI_TXN_INFO.STATUS AS "Status",
		DCI_TXN_INFO.DESCRIPTION AS "Description",
		DCI_TXN_INFO.FAULT_CODE || '-' || DCI_TXN_INFO.FAULT_STRING AS "Posting Error",
		DCI_TXN_INFO.INTERBANK_SETTLE_AMT AS "Amount",
		DCI_TXN_INFO.CDTR_ACCT_OTHR_ID AS "Beneficiary Account",
		DCI_TXN_INFO.CDTR_NAME AS "Beneficiary Name",
		DCI_GP_HEADER_INFO.PMT_TP_INF_CTGY_PURP_PRTRY AS "Batch Purpose",
		DCI_TXN_INFO.PURP_PROPTYCHAR AS "Transaction Purpose",
		DCI_TXN_INFO.DBTR_ACCT_OTHR_ID AS "Ordering Customer Account",
		DCI_TXN_INFO.DBTR_NAME AS "Oedering Customer Name"
FROM 	DCI_TXN_INFO
INNER 	JOIN DCI_GP_HEADER_INFO 
		ON DCI_TXN_INFO.DCI_GP_HDR_ID_TXN_FK=DCI_GP_HEADER_INFO.DCI_GP_HEADER_ID
WHERE   DCI_GP_HEADER_INFO.INTERBANK_SETTLE_DATE = to_date('2017-11-30 00:00:00', 'yyyy-mm-dd hh24-mi-ss') AND
		DCI_TXN_INFO.STATUS LIKE 'DCI_FAILED'

		SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		DCO_TXN_INFO.CBO_GRP_STATUS AS "CBO Group Status",
		DCO_TXN_INFO.STATUS  AS "Status",
		DCO_TXN_INFO.DESCRIPTION AS "Description",
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE DCO_TXN_INFO.BENEF_ACC LIKE '004010001076%'


SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		DCO_TXN_INFO.CBO_GRP_STATUS AS "CBO Group Status",
		DCO_TXN_INFO.STATUS  AS "Status",
		DCO_TXN_INFO.DESCRIPTION AS "Description",
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE 	DCO_TXN_INFO.MSG_ID = 'BMCT0IA001259'


SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		DCO_TXN_INFO.STATUS  AS "Original Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.STATUS, '-')  AS "Cancel Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.DESCRIPTION, DCO_TXN_INFO.DESCRIPTION) AS "Description",
		coalesce(CANO_REVO_RETO_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE || '-' || CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "Cancelation Error", 
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
LEFT	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171129T12:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171130T12:00:00.000'
		
		
		SELECT * FROM DCO_TXN_INFO WHERE DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK ='6576'
		SELECT * FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '310117112900010%'
		
		
		
		
SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.STATUS, DCO_TXN_INFO.STATUS)  AS "Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.DESCRIPTION, DCO_TXN_INFO.DESCRIPTION) AS "Description",
		coalesce(CANO_REVO_RETO_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE || '-' || CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "Cancelation Error", 
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
LEFT	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID
WHERE   MSG_RCV_TIMESTAMP >= '20171130T11:00:00.000' AND
		MSG_RCV_TIMESTAMP <= '20171206T12:00:00.000' AND
		DCO_TXN_INFO.CBO_TXN_STATUS IN ('RJCT 1001', 'RJCT 1009') AND 
		DCO_TXN_INFO.STATUS LIKE 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT'

		
		
SELECT 	* 
FROM 	DCO_TXN_INFO 
WHERE 	STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT' AND 
		CBO_GRP_STATUS IN ('RJCT 1001', 'RJCT 1009');

UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_SEND_TO_CBO_PT' 
WHERE 	STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT' AND 
		CBO_GRP_STATUS IN ('RJCT 1001', 'RJCT 1009');
		
UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_SEND_TO_CBO_PT' 
WHERE	MSG_ID LIKE 'OMAB0IJ010072'
		
SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.STATUS, DCO_TXN_INFO.STATUS)  AS "Status",
		coalesce(CANO_REVO_RETO_TXN_INFO.DESCRIPTION, DCO_TXN_INFO.DESCRIPTION) AS "Description",
		coalesce(CANO_REVO_RETO_TXN_INFO.CBS_PAY_REF, '-') AS "Cancelation Posting Reference",
		CANO_REVO_RETO_TXN_INFO.CBS_FAULT_CODE || '-' || CANO_REVO_RETO_TXN_INFO.CBS_FAULT_STRING AS "Cancelation Error", 
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
LEFT	JOIN CANO_REVO_RETO_TXN_INFO
		ON CANO_REVO_RETO_TXN_INFO.ORIGIN_END_TO_END_ID=DCO_TXN_INFO.END_TO_END_ID

UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_SEND_TO_CBO_PT' 
WHERE	END_TO_END_ID LIKE 'LBT3101171130'


SELECT 	*
FROM 	DCO_GROUP_HEADER_INFO
WHERE   DCO_GRP_HEADER_ID LIKE '6787'

UPDATE	DCO_GROUP_HEADER_INFO
SET CURRENCY = 'OMR'
WHERE   DCO_GRP_HEADER_ID LIKE '6787'


	
SELECT 	*
FROM 	DCO_GROUP_HEADER_INFO.CHANNEL = 'SO'   
BATCH_REFERENCE LIKE '012661700%'

SELECT 	*
FROM 	DCO_TXN_INFO
WHERE   DCO_GRP_HDR_ID_TXN_INFO_FK LIKE '6559'

SELECT 	COUNT(*)
FROM 	DCO_TXN_INFO
WHERE   DCO_GRP_HDR_ID_TXN_INFO_FK LIKE '6559'

UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_SEND_TO_CBO_PT'
WHERE   DCO_GRP_HDR_ID_TXN_INFO_FK LIKE '6559'

 

 
SELECT 	*
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE 	DCO_TXN_INFO.STATUS = 'DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT';

          45828                       6559 1       NULL     17475.179 BMUSOMRX   0423010782990038 MAZOON ELECTRICITY COMPANY SAOC NULL     NULL          1003             NULL            DCO_SENT_TO_CBO_NPT/DCO_SENT_TO_CBO_PT Transaction is sent to CBO in a Batch Message NULL         NULL        NULL      LBT31401711300000551 OMAB0I3SQ0054 OMAB0I3SQ0054001 NULL           NULL       NULL         NULL           NULL                             6559 LBT     NORM      3140171130000055 3101062945500             SHARQIYAH DESALINATION CO SAOG 1011277              003                       010                 OMR      DCO_CBS_SUCCESS_PT Message has been received from OAB channel 20171130T12:29:43.043+12:29 PassThru    LBT3140171130000055 <AchDirectCredit OptionIdentifier="PassThru"><Channel>LBT</Channel><BatchReference>3140171130000055</BatchReference><OrderingCustomerAccount>3101062945500</OrderingCustomerAccount><OrderingCustomerName>SHARQIYAH DESALINATION CO SAOG</OrderingCustomerName><OrderingCustomerId>1011277</OrderingCustomerId><OrderingCustomerIdType>003</OrderingCustomerIdType><PurposeOfTransfer>010</PurposeOfTransfer><Priority>NORM</Priority><Currency>OMR</Currency><Transaction><TransactionReference>1</TransactionReference><UserReference/><Amount>17475.179</Amount><BeneficiaryBank>BMUSOMRX</BeneficiaryBank><BeneficiaryAccount>0423010782990038</BeneficiaryAccount><BeneficiaryName>MAZOON ELECTRICITY COMPANY SAOC</BeneficiaryName><BeneficiaryId/><BeneficiaryIdType/><PurposeOfTransfer>1003</PurposeOfTransfer><DetailsOfPayments/></Transaction></AchDirectCredit> NULL         NULL        NULL       NULL         NULL                NULL           NULL


SELECT * FROM 	DCO_TXN_INFO 
WHERE   END_TO_END_ID =  'LBT31601711300000451'

UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_SEND_TO_CBO_PT'
WHERE   END_TO_END_ID = 'LBT31601711300000451'



SELECT 	*
FROM CANO_REVO_RETO_GRPHDR_INFO
WHERE GRP_ORGIN_BATCH LIKE '310171130H00272%'


SELECT 	*
FROM CANO_REVO_RETO_TXN_INFO
WHERE ORIGIN_END_TO_END_ID LIKE 'CLP310171130H0027201%'

DELETE
FROM CANO_REVO_RETO_GRPHDR_INFO
WHERE GRP_ORGIN_BATCH LIKE '310171130H00272%'

DELETE
FROM CANO_REVO_RETO_TXN_INFO
WHERE ORIGIN_END_TO_END_ID LIKE 'CLP310171130H0027201%'

UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_RCVD'
WHERE   DCO_GRP_HDR_ID_TXN_INFO_FK LIKE '7094'


UPDATE 	DCO_TXN_INFO 
SET 	STATUS = 'DCO_CBS_CRDT_OC_SUCCESS', CBO_TXN_STATUS = 'RJCT 1001'
WHERE	DCO_GRP_HDR_ID_TXN_INFO_FK = '5601'

SELECT * FROM DCO_TXN_INFO
WHERE	DCO_GRP_HDR_ID_TXN_INFO_FK = '5601'		


SELECT 	DCO_GROUP_HEADER_INFO.MSG_RCV_TIMESTAMP AS "Transaction Timestamp", 
		DCO_GROUP_HEADER_INFO.CHANNEL AS "Channel", 
		DCO_GROUP_HEADER_INFO.BATCH_REFERENCE AS "OAB Batch Reference",
		DCO_TXN_INFO.TXN_REF AS "OAB Transaction Reference",
		DCO_TXN_INFO.MSG_ID AS "CBO Batch Reference",
		DCO_TXN_INFO.TXN_ID AS "CBO Transaction Reference",
		DCO_TXN_INFO.END_TO_END_ID AS "CBO End-to-End Reference",
		DCO_TXN_INFO.CBO_TXN_STATUS AS "CBO Status",
		DCO_TXN_INFO.CBO_GRP_STATUS AS "CBO Group Status",
		DCO_TXN_INFO.STATUS  AS "Status",
		DCO_TXN_INFO.DESCRIPTION AS "Description",
		DCO_TXN_INFO.AMOUNT AS "Amount",
		DCO_TXN_INFO.BENEF_BANK AS "Beneficiary Bank", 
		DCO_TXN_INFO.BENEF_ACC AS "Beneficiary Account",
		DCO_TXN_INFO.BENEF_NAME AS "Beneficiary Name",
		DCO_GROUP_HEADER_INFO.PURPOSE_OF_TRANSFER AS "Batch Purpose",
		DCO_TXN_INFO.PURP_OF_TRANSFER AS "Transaction Purpose",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_ACCOUNT AS "Ordering Customer Account",
		DCO_GROUP_HEADER_INFO.ORDERING_CUSTOMER_NAME AS "Oedering Customer Name"
FROM 	DCO_TXN_INFO
INNER 	JOIN DCO_GROUP_HEADER_INFO 
		ON DCO_TXN_INFO.DCO_GRP_HDR_ID_TXN_INFO_FK=DCO_GROUP_HEADER_INFO.DCO_GRP_HEADER_ID
WHERE 	DCO_GROUP_HEADER_INFO.BATCH_REFERENCE = '31011711290001X1';
