--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."CANI_UNDRLYG_CANC_RSN_INFO" (
		"CANC_UNDRLYG_CANC_RSN_INFO_ID" NUMBER NOT NULL,
		"CANC_UNDRLYG_ID_CAN_RSN_INF_FK" NUMBER,
		"CANC_RSN_INFO_RSN_PRTRY" VARCHAR2(35 CHAR),
		"CANC_RSN_INFO_ADDTL_INFO" VARCHAR2(105 CHAR)
	)
	LOGGING;

ALTER TABLE "ESBACH"."CANI_UNDRLYG_CANC_RSN_INFO" ADD CONSTRAINT "SYS_C0011547" CHECK ("CANC_UNDRLYG_CANC_RSN_INFO_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."CANI_UNDRLYG_CANC_RSN_INFO" ADD CONSTRAINT "SYS_C0011548" PRIMARY KEY
	("CANC_UNDRLYG_CANC_RSN_INFO_ID");

ALTER TABLE "ESBACH"."CANI_UNDRLYG_CANC_RSN_INFO" ADD CONSTRAINT "SYS_C0011549" FOREIGN KEY
	("CANC_UNDRLYG_ID_CAN_RSN_INF_FK")
	REFERENCES "ESBACH"."CANI_UNDERLYING"
	("CANC_UNDRLYG_ID");

CREATE TRIGGER "ESBACH"."CANI_UND_CANC_RSN_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."CANI_UNDRLYG_CANC_RSN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
    
    SELECT CANI_UND_CANC_RSN_INFO_SEQ.NEXTVAL INTO :NEW.CANC_UNDRLYG_CANC_RSN_INFO_ID FROM SYS.DUAL;
END;

