--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."CANI_SUPPLEMENTARY_DATA" (
		"CANC_SUPPLEMENTARY_DATA_ID" NUMBER NOT NULL,
		"CANC_ASSIGNMENT_ID_SUPP_FK" NUMBER,
		"PLACE_NAME" VARCHAR2(350 CHAR),
		"ENV_BATCH_SRC" VARCHAR2(40 CHAR)
	)
	LOGGING;

ALTER TABLE "ESBACH"."CANI_SUPPLEMENTARY_DATA" ADD CONSTRAINT "SYS_C0011390" CHECK ("CANC_SUPPLEMENTARY_DATA_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."CANI_SUPPLEMENTARY_DATA" ADD CONSTRAINT "SYS_C0011391" PRIMARY KEY
	("CANC_SUPPLEMENTARY_DATA_ID");

ALTER TABLE "ESBACH"."CANI_SUPPLEMENTARY_DATA" ADD CONSTRAINT "SYS_C0011392" FOREIGN KEY
	("CANC_ASSIGNMENT_ID_SUPP_FK")
	REFERENCES "ESBACH"."CANI_ASSIGNMENT"
	("CANC_ASSIGNMENT_ID");

CREATE TRIGGER "ESBACH"."CANI_SUPPLEMENTARY_DATA_TRIG" 
	BEFORE INSERT ON "ESBACH"."CANI_SUPPLEMENTARY_DATA"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
   SELECT CANI_SUPP_DATA_SEQ.NEXTVAL INTO :NEW.CANC_SUPPLEMENTARY_DATA_ID FROM SYS.DUAL;
END;

