--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."CANI_TXN_CANC_RSN_INFO" (
		"CANC_TXN_CANC_RSN_INFO_ID" NUMBER NOT NULL,
		"CANC_TXN_ID_CANC_RSN_INFO_FK" NUMBER,
		"CANC_RSN_INFO_RSN_PRTRY" VARCHAR2(35 CHAR),
		"CANC_RSN_INFO_ADDTL_INFO" VARCHAR2(105 CHAR)
	)
	LOGGING;

ALTER TABLE "ESBACH"."CANI_TXN_CANC_RSN_INFO" ADD CONSTRAINT "SYS_C0011541" CHECK ("CANC_TXN_CANC_RSN_INFO_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."CANI_TXN_CANC_RSN_INFO" ADD CONSTRAINT "SYS_C0011542" PRIMARY KEY
	("CANC_TXN_CANC_RSN_INFO_ID");

ALTER TABLE "ESBACH"."CANI_TXN_CANC_RSN_INFO" ADD CONSTRAINT "SYS_C0011543" FOREIGN KEY
	("CANC_TXN_ID_CANC_RSN_INFO_FK")
	REFERENCES "ESBACH"."CANI_TXN_INFO"
	("CANC_TXN_INFO_ID");

CREATE TRIGGER "ESBACH"."CANI_TXN_CANC_RSN_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."CANI_TXN_CANC_RSN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
    SELECT CANI_TXN_CANC_RSN_INFO_SEQ.NEXTVAL INTO :NEW.CANC_TXN_CANC_RSN_INFO_ID FROM SYS.DUAL;
END;

