--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."DC_CONFIG_VALUES" (
		"DC_CONFIG_ID" NUMBER,
		"STML_MTHD" VARCHAR2(4),
		"CLRSYS_PRPRTRY" VARCHAR2(3),
		"INSTAGT_FN_BICFI" VARCHAR2(10),
		"CHRG_BEARER" VARCHAR2(4),
		"SCHMA_NM_PRPRTRY" VARCHAR2(16),
		"DBTR_ACCNO_TYPE" VARCHAR2(8),
		"DBTRAGT_FN_BICFI" VARCHAR2(10),
		"CDTR_ACCNO_TYPE" VARCHAR2(8),
		"SUPP_PLCNAME" VARCHAR2(20),
		"DC_STLMNT_ACC" VARCHAR2(30 CHAR),
		"DD_STLMNT_ACC" VARCHAR2(30 CHAR),
		"ACH_DC_IFSC" VARCHAR2(10 CHAR),
		"BANK_PREFIX" VARCHAR2(10),
		"PMTINFO_CTPURP_PRTRY" VARCHAR2(10),
		"MAX_NO_OF_TXNS" NUMBER(5 , 0),
		"MAX_TOTAL_AMOUNT" NUMBER(18 , 5)
	)
	LOGGING;

