--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."DCI_GP_HEADER_INFO" (
		"DCI_GP_HEADER_ID" NUMBER NOT NULL,
		"MSG_ID" VARCHAR2(35 CHAR),
		"CREATION_DATETIME" TIMESTAMP,
		"NO_OF_TXNS" NUMBER,
		"TOTAL_INTRBANK_SETTLE_AMT" NUMBER(18 , 5),
		"INTERBANK_SETTLE_DATE" DATE,
		"SETTLE_INFO_METHOD" VARCHAR2(10 CHAR) DEFAULT 'CLRG' NOT NULL,
		"SETTLE_INFO_CLR_SYS_PRTY" VARCHAR2(10 CHAR) DEFAULT 'CBO' NOT NULL,
		"PMT_TP_INF_LCL_INST_CODE" VARCHAR2(40 CHAR),
		"PMT_TP_INF_CTGY_PURP_PRTRY" VARCHAR2(35 CHAR),
		"INST_AGT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"INSTG_AGT_BRNCHID_ID" VARCHAR2(35 CHAR),
		"INSTD_AGT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"INSTD_AGT_BRNCHID_ID" VARCHAR2(35 CHAR),
		"SRC_MSG" CLOB
	)
	LOGGING;

ALTER TABLE "ESBACH"."DCI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011499" CHECK ("DCI_GP_HEADER_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."DCI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011500" CHECK ("SETTLE_INFO_METHOD" IS NOT NULL);

ALTER TABLE "ESBACH"."DCI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011501" CHECK ("SETTLE_INFO_CLR_SYS_PRTY" IS NOT NULL);

ALTER TABLE "ESBACH"."DCI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011502" PRIMARY KEY
	("DCI_GP_HEADER_ID");

CREATE TRIGGER "ESBACH"."DCI_GP_HEADER_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."DCI_GP_HEADER_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  
   
   SELECT DCI_GP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.DCI_GP_HEADER_ID FROM SYS.DUAL;
END;

