--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."DCI_TXN_INFO" (
		"DCI_TXN_INFO_ID" NUMBER NOT NULL,
		"DCI_GP_HDR_ID_TXN_FK" NUMBER,
		"PMT_ID_INSTR_ID" VARCHAR2(35 CHAR),
		"PMT_ID_ENDTOEND_ID" VARCHAR2(30 CHAR),
		"PMT_ID_TXN_ID" VARCHAR2(40 CHAR),
		"INTERBANK_SETTLE_AMT" NUMBER(18 , 5),
		"STLMT_PRITRY" VARCHAR2(40 CHAR),
		"CHARGE_BEARER" VARCHAR2(10 CHAR) DEFAULT 'SLEV' NOT NULL,
		"INSTD_AGT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"INSTD_AGT_BNCHID_ID" VARCHAR2(35 CHAR),
		"DBTR_NAME" VARCHAR2(140 CHAR),
		"DBTR_ACCT_ID_IBAN" VARCHAR2(30 CHAR),
		"DBTR_ACCT_OTHR_ID" VARCHAR2(34 CHAR),
		"DBTR_ACCT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"DBTR_ACCT_BNCHID_ID" VARCHAR2(35 CHAR),
		"CDTR_NAME" VARCHAR2(140 CHAR),
		"CDTR_ACCT_ID_IBAN" VARCHAR2(30 CHAR),
		"CDTR_ACCT_OTHR_ID" VARCHAR2(34 CHAR),
		"CDTR_ACCT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"CDTR_ACCT_BNCHID_ID" VARCHAR2(35 CHAR),
		"PURP_PROPTYCHAR" VARCHAR2(35 CHAR),
		"STATUS" VARCHAR2(40 CHAR),
		"CBS_TRAN_REF" VARCHAR2(40 CHAR),
		"CBS_PAY_REF" VARCHAR2(35 CHAR),
		"EXEC_DESC" VARCHAR2(2000),
		"DESCRIPTION" VARCHAR2(100),
		"MSG_ID" VARCHAR2(20 CHAR),
		"CBS_REQUEST_MESSAGE" CLOB,
		"FAULT_CODE" VARCHAR2(20),
		"FAULT_STRING" VARCHAR2(500),
		"TXN_ID" VARCHAR2(25 CHAR),
		"CBO_GRP_STATUS" VARCHAR2(40),
		"CBO_TXN_STATUS" VARCHAR2(150)
	)
	LOGGING;

ALTER TABLE "ESBACH"."DCI_TXN_INFO" ADD CONSTRAINT "SYS_C0011503" CHECK ("DCI_TXN_INFO_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."DCI_TXN_INFO" ADD CONSTRAINT "SYS_C0011504" CHECK ("CHARGE_BEARER" IS NOT NULL);

ALTER TABLE "ESBACH"."DCI_TXN_INFO" ADD CONSTRAINT "SYS_C0011505" PRIMARY KEY
	("DCI_TXN_INFO_ID");

ALTER TABLE "ESBACH"."DCI_TXN_INFO" ADD CONSTRAINT "SYS_C0011506" FOREIGN KEY
	("DCI_GP_HDR_ID_TXN_FK")
	REFERENCES "ESBACH"."DCI_GP_HEADER_INFO"
	("DCI_GP_HEADER_ID");

CREATE TRIGGER "ESBACH"."DCI_TXN_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."DCI_TXN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
    SELECT DCI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.DCI_TXN_INFO_ID FROM SYS.DUAL;
END;

