--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."DCO_TXN_INFO" (
		"DCO_TXN_INF_ID" NUMBER NOT NULL,
		"DCO_GRP_HDR_ID_TXN_INFO_FK" NUMBER NOT NULL,
		"TXN_REF" VARCHAR2(16 CHAR),
		"USER_REF" VARCHAR2(35 CHAR),
		"AMOUNT" NUMBER(18 , 5),
		"BENEF_BANK" VARCHAR2(35 CHAR),
		"BENEF_ACC" VARCHAR2(30 CHAR),
		"BENEF_NAME" VARCHAR2(140 CHAR),
		"BENEF_ID" VARCHAR2(35 CHAR),
		"BENEF_ID_TYPE" VARCHAR2(35 CHAR),
		"PURP_OF_TRANSFER" VARCHAR2(10 CHAR),
		"DETAILS_OF_PMTS" VARCHAR2(140 CHAR),
		"STATUS" VARCHAR2(50 CHAR),
		"DESCRIPTION" VARCHAR2(500 CHAR),
		"CBS_TRAN_REF" VARCHAR2(40 CHAR),
		"CBS_PAY_REF" VARCHAR2(40 CHAR),
		"EXEC_DESC" VARCHAR2(2000 CHAR),
		"END_TO_END_ID" VARCHAR2(48 CHAR),
		"MSG_ID" VARCHAR2(25 CHAR),
		"TXN_ID" VARCHAR2(25 CHAR),
		"CBO_GRP_STATUS" VARCHAR2(40),
		"FAULT_CODE" VARCHAR2(40),
		"FAULT_STRING" VARCHAR2(500),
		"CBO_TXN_STATUS" VARCHAR2(40),
		"CBS_REQUEST_MESSAGE" CLOB
	)
	LOGGING;

CREATE UNIQUE INDEX "ESBACH"."DCO_TXN_INFO_PK"
	ON "ESBACH"."DCO_TXN_INFO"
	("DCO_TXN_INF_ID"		ASC)
	LOGGING;

ALTER TABLE "ESBACH"."DCO_TXN_INFO" ADD CONSTRAINT "DCO_TXN_INFO_PK" PRIMARY KEY
	("DCO_TXN_INF_ID");

ALTER TABLE "ESBACH"."DCO_TXN_INFO" ADD CONSTRAINT "SYS_C0011485" CHECK ("DCO_GRP_HDR_ID_TXN_INFO_FK" IS NOT NULL);

ALTER TABLE "ESBACH"."DCO_TXN_INFO" ADD CONSTRAINT "DCO_GRP_HDR_ID_TXN_INFO_FK" FOREIGN KEY
	("DCO_GRP_HDR_ID_TXN_INFO_FK")
	REFERENCES "ESBACH"."DCO_GROUP_HEADER_INFO"
	("DCO_GRP_HEADER_ID");

CREATE TRIGGER "ESBACH"."DCO_TXN_INFO_TRG" 
	BEFORE INSERT ON "ESBACH"."DCO_TXN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  
   SELECT DCO_TXN_INFO_SEQ.NEXTVAL INTO :NEW.DCO_TXN_INF_ID FROM SYS.DUAL;
END;

