--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."DCO_GROUP_HEADER_INFO" (
		"DCO_GRP_HEADER_ID" NUMBER NOT NULL,
		"CHANNEL" VARCHAR2(16 CHAR),
		"PRIORITY1" VARCHAR2(4),
		"BATCH_REFERENCE" VARCHAR2(16 CHAR),
		"ORDERING_CUSTOMER_ACCOUNT" VARCHAR2(30 CHAR),
		"ORDERING_CUSTOMER_NAME" VARCHAR2(140),
		"ORDERING_CUSTOMER_ID" VARCHAR2(35 CHAR),
		"ORDERING_CUSTOMER_ID_TYPE" VARCHAR2(35 CHAR),
		"PURPOSE_OF_TRANSFER" VARCHAR2(3 CHAR),
		"CURRENCY" VARCHAR2(3 CHAR),
		"STATUS" VARCHAR2(60),
		"DESCRIPTION" VARCHAR2(500 CHAR),
		"MSG_RCV_TIMESTAMP" VARCHAR2(40),
		"OPTIONAL_ID" VARCHAR2(20 CHAR),
		"CHL_BTCH_REF" VARCHAR2(32 CHAR),
		"MSG_CHANNEL_TO_ESB" CLOB,
		"CBS_TRAN_REF" VARCHAR2(40),
		"CBS_PAY_REF" VARCHAR2(30),
		"FAULT_CODE" VARCHAR2(40),
		"FAULT_STRING" VARCHAR2(100),
		"CBS_REQUEST_MESSAGE" CLOB,
		"MSG_ESB_TO_CBO" CLOB,
		"MSG_CBO_TO_ESB" CLOB
	)
	LOGGING;

CREATE UNIQUE INDEX "ESBACH"."DCO_GRP_HEADER_INFO_PK"
	ON "ESBACH"."DCO_GROUP_HEADER_INFO"
	("DCO_GRP_HEADER_ID"		ASC)
	LOGGING;

ALTER TABLE "ESBACH"."DCO_GROUP_HEADER_INFO" ADD CONSTRAINT "DCO_GRP_HEADER_INFO_PK" PRIMARY KEY
	("DCO_GRP_HEADER_ID");

CREATE TRIGGER "ESBACH"."DCO_GROUP_HEADER_INFO_TRG" 
	BEFORE INSERT ON "ESBACH"."DCO_GROUP_HEADER_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  
   SELECT DCO_GROUP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.DCO_GRP_HEADER_ID FROM SYS.DUAL;
END;

