--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."DDO_GROUP_HEADER_INFO" (
		"DDO_GRP_HEADER_ID" NUMBER NOT NULL,
		"MSG_RCV_TIMESTAMP" VARCHAR2(50),
		"CHANNEL" VARCHAR2(16 CHAR),
		"PRIORITY" NUMBER(3 , 0),
		"BATCH_REFERENCE" VARCHAR2(16 CHAR),
		"ORDERING_CUSTOMER_ACCOUNT" VARCHAR2(30 CHAR),
		"ORDERING_CUSTOMER_NAME" VARCHAR2(140 CHAR),
		"ORDERING_CUSTOMER_ID" VARCHAR2(35 CHAR),
		"ORDERING_CUSTOMER_ID_TYPE" VARCHAR2(35 CHAR),
		"PURPOSE_OF_TRANSFER" VARCHAR2(10 CHAR),
		"CURRENCY" VARCHAR2(3 CHAR),
		"STATUS" VARCHAR2(35 CHAR),
		"DESCRIPTION" VARCHAR2(500 CHAR),
		"CHL_BATCH_REF" VARCHAR2(30),
		"OPT_ID" VARCHAR2(10 CHAR),
		"CBO_STATUS" VARCHAR2(40),
		"MSG_CHANNEL_TO_ESB" CLOB,
		"MSG_ESB_TO_CBO" CLOB,
		"MSG_CBO_TO_ESB" CLOB
	)
	LOGGING;

CREATE UNIQUE INDEX "ESBACH"."DD_GRP_HEADER_INFO_PK"
	ON "ESBACH"."DDO_GROUP_HEADER_INFO"
	("DDO_GRP_HEADER_ID"		ASC)
	LOGGING;

ALTER TABLE "ESBACH"."DDO_GROUP_HEADER_INFO" ADD CONSTRAINT "DD_GRP_HEADER_INFO_PK" PRIMARY KEY
	("DDO_GRP_HEADER_ID");

CREATE TRIGGER "ESBACH"."DDO_GROUP_HEADER_INFO_TRG" 
	BEFORE INSERT ON "ESBACH"."DDO_GROUP_HEADER_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  
   
   SELECT DDO_GROUP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.DDO_GRP_HEADER_ID FROM SYS.DUAL;
END;

