--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."PRI_TXN_INFO" (
		"PR_TXN_INFO_ID" NUMBER NOT NULL,
		"PR_GP_HEADER_ID_TXN_FK" NUMBER,
		"RTR_ID" VARCHAR2(16 CHAR),
		"ORGNL_TX_ID" VARCHAR2(16 CHAR),
		"RTRD_INTR_BK_STTLM_AMT" NUMBER,
		"STATUS" VARCHAR2(30),
		"CBS_TRAN_REF" VARCHAR2(100 CHAR),
		"ACCOUNT" VARCHAR2(30 CHAR),
		"EXEC_DESC" VARCHAR2(2000 CHAR),
		"CBS_PAY_REF" VARCHAR2(100 CHAR),
		"DESCRIPTION" VARCHAR2(2000),
		"MSG_ID" VARCHAR2(50),
		"CBS_REQUEST" CLOB,
		"FAULT_CODE" VARCHAR2(30),
		"FAULT_STRING" VARCHAR2(500),
		"TXN_ID" VARCHAR2(25 CHAR),
		"CBO_GRP_STATUS" VARCHAR2(40),
		"CBO_TXN_STATUS" VARCHAR2(150)
	)
	LOGGING;

ALTER TABLE "ESBACH"."PRI_TXN_INFO" ADD CONSTRAINT "SYS_C0011511" CHECK ("PR_TXN_INFO_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."PRI_TXN_INFO" ADD CONSTRAINT "SYS_C0011512" PRIMARY KEY
	("PR_TXN_INFO_ID");

CREATE TRIGGER "ESBACH"."PRI_TXN_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."PRI_TXN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
      SELECT PRI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.PR_TXN_INFO_ID FROM SYS.DUAL;
    
END;

