--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."REVI_GRP_HEADER_INFO" (
		"REV_GRP_HEADER_ID" NUMBER NOT NULL,
		"MSG_ID" VARCHAR2(16 CHAR),
		"CREATION_DATETIME" VARCHAR2(30),
		"NO_OF_TXNS" NUMBER,
		"TOTAL_INTRBANK_SETTLE_AMT" NUMBER(18 , 5),
		"INTERBANK_SETTLE_DATE" CHAR(20),
		"SETTLE_INFO_METHOD" VARCHAR2(35 CHAR) DEFAULT 'CLRG' NOT NULL,
		"SETTLE_INFO_CLR_SYS_PRTRY" VARCHAR2(35 CHAR) DEFAULT 'CBO' NOT NULL,
		"INSTG_AGT_FIN_ID_BICFI" VARCHAR2(20 CHAR),
		"INSTG_AGT_FIN_ID_CLR_SYS_MMBID" VARCHAR2(35 CHAR),
		"INSTG_AGT_BRNCHID_ID" VARCHAR2(35 CHAR),
		"INSTD_AGT_FIN_ID_BICFI" VARCHAR2(20 CHAR),
		"INSTD_AGT_FIN_ID_CLR_SYS_MMBID" VARCHAR2(35 CHAR),
		"INSTD_AGT_BRNCHID_ID" VARCHAR2(35 CHAR),
		"SOURCE_SYS_CODE" VARCHAR2(20 CHAR),
		"SOURCE_SYS_ID" VARCHAR2(20 CHAR),
		"INTERFACE_CODE" VARCHAR2(20 CHAR),
		"SOURCE_SYS_TIMESTAMP" TIMESTAMP
	)
	LOGGING;

ALTER TABLE "ESBACH"."REVI_GRP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011517" CHECK ("REV_GRP_HEADER_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."REVI_GRP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011518" CHECK ("SETTLE_INFO_METHOD" IS NOT NULL);

ALTER TABLE "ESBACH"."REVI_GRP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011519" CHECK ("SETTLE_INFO_CLR_SYS_PRTRY" IS NOT NULL);

ALTER TABLE "ESBACH"."REVI_GRP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011520" PRIMARY KEY
	("REV_GRP_HEADER_ID");

CREATE TRIGGER "ESBACH"."REVI_GRP_HEADER_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."REVI_GRP_HEADER_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
    
   
    SELECT REVI_GRP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.REV_GRP_HEADER_ID FROM SYS.DUAL;
END;

