--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."WPS_SIF_HEADER_INFO" (
		"WPS_SIF_HEADER_INFO_ID" NUMBER NOT NULL,
		"SIF_CBO_FILE_NAME" VARCHAR2(200 CHAR),
		"EMPLOYEER_CRNO" VARCHAR2(20 CHAR),
		"PAYER_CRNO" VARCHAR2(20 CHAR),
		"PAYER_BANK_SHORT_NAME" VARCHAR2(4 CHAR),
		"PAYER_ACCOUNT_NO" VARCHAR2(30 CHAR),
		"SALARY_YEAR" VARCHAR2(4 CHAR),
		"SALARY_MONTH" VARCHAR2(2 CHAR),
		"TOTAL_SALARIES" VARCHAR2(30 CHAR),
		"NO_OF_RECORDS" VARCHAR2(10 CHAR),
		"ESB_STATUS" VARCHAR2(100 CHAR),
		"EXEC_DESC" VARCHAR2(4000 CHAR),
		"CBS_TXN_REF" VARCHAR2(30),
		"PAYMENT_TYPE" VARCHAR2(20 CHAR),
		"CBS_PAY_REF" VARCHAR2(50),
		"CBS_FAULT_CODE" VARCHAR2(20),
		"CBS_FAULT_STRING" VARCHAR2(500),
		"CBO_STATUS" VARCHAR2(50),
		"SIF_CHL_FILE_NAME" VARCHAR2(50),
		"SIF_ACK_RESPONSE" CLOB,
		"REP_ACK_RESPONSE" CLOB,
		"SYNC_BACK_RESPONSE" CLOB,
		"CHL_REFERENCE" VARCHAR2(30),
		"OPTIONALIDENTIFIER" VARCHAR2(20),
		"CBS_REQUEST_MESSAGE" CLOB,
		"ERROR_LIST" CLOB
	)
	LOGGING;

ALTER TABLE "ESBACH"."WPS_SIF_HEADER_INFO" ADD CONSTRAINT "SYS_C0011531" CHECK ("WPS_SIF_HEADER_INFO_ID" IS NOT NULL);

ALTER TABLE "ESBACH"."WPS_SIF_HEADER_INFO" ADD CONSTRAINT "SYS_C0011532" PRIMARY KEY
	("WPS_SIF_HEADER_INFO_ID");

CREATE TRIGGER "ESBACH"."WPS_SIF_HEADER_INFO_TRIG" 
	BEFORE INSERT ON "ESBACH"."WPS_SIF_HEADER_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   SELECT WPS_SIF_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.WPS_SIF_HEADER_INFO_ID FROM SYS.DUAL;
END;

