
drop table "ESBACH"."CANI_TXN_INFO"

  CREATE TABLE "ESBACH"."CANI_TXN_INFO" 
   (	"CANC_TXN_INFO_ID" NUMBER NOT NULL ENABLE, 
	"CANC_ASSIGNMENT_ID_TXN_FK" NUMBER, 
	"CANC_ID" VARCHAR2(35 CHAR), 
	"ORGNL_TX_ID" VARCHAR2(35 CHAR), 
	"STATUS" VARCHAR2(50 CHAR), 
	"CBS_TRAN_REF" VARCHAR2(40 CHAR), 
	"ACC_NUMBER" VARCHAR2(30 CHAR), 
	"AMOUNT" NUMBER(18,2), 
	"STATUS_TRAIL" VARCHAR2(40 BYTE), 
	"CBS_PAY_REF" VARCHAR2(35 BYTE), 
	"EXEC_DESC" VARCHAR2(2000 BYTE), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"ASSIGN_ID" VARCHAR2(20 CHAR), 
	"FAULT_CODE" VARCHAR2(20 BYTE), 
	"FAULT_STRING" VARCHAR2(50 BYTE), 
	"CBS_REQUEST_MESSAGE" CLOB, 
	 PRIMARY KEY ("CANC_TXN_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("CANC_ASSIGNMENT_ID_TXN_FK")
	  REFERENCES "ESBACH"."CANI_ASSIGNMENT" ("CANC_ASSIGNMENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CBS_REQUEST_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  
  
  
  
    
   CREATE SEQUENCE  "ESBACH"."CANI_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7501 CACHE 500 NOORDER  NOCYCLE ;

  
  
  CREATE OR REPLACE TRIGGER "ESBACH"."CANI_TXN_INFO_TRIG" 
   before INSERT
   ON esbach.CANI_TXN_INFO
   FOR EACH ROW
BEGIN
   
    SELECT CANI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.CANC_TXN_INFO_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."CANI_TXN_INFO_TRIG" ENABLE;
