drop table "ESBACH"."CANI_UNDERLYING" 
  CREATE TABLE "ESBACH"."CANI_UNDERLYING" 
   (	"CANC_UNDRLYG_ID" NUMBER NOT NULL ENABLE, 
	"CANC_ASSIGNMENT_ID_UNDRLYG_FK" NUMBER, 
	"ORG_GP_INF_AND_CANC_GP_CANC_ID" VARCHAR2(35 CHAR), 
	"ORG_GP_INF_AND_CANC_ORG_MSG_ID" VARCHAR2(35 CHAR), 
	"ORG_GP_INF_AND_CAN_ORG_MGNM_ID" VARCHAR2(35 CHAR), 
	"ORG_GP_INF_AND_CANC_NO_OF_TXS" NUMBER, 
	"ORG_GP_INF_AND_CANC_GP_CANC" VARCHAR2(10 CHAR), 
	 PRIMARY KEY ("CANC_UNDRLYG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("CANC_ASSIGNMENT_ID_UNDRLYG_FK")
	  REFERENCES "ESBACH"."CANI_ASSIGNMENT" ("CANC_ASSIGNMENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
  
   CREATE SEQUENCE  "ESBACH"."CANI_UNDERLYING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7001 CACHE 500 NOORDER  NOCYCLE ;

  
  CREATE OR REPLACE TRIGGER "ESBACH"."CANI_UNDERLYING_TRIG" 
   before INSERT
   ON esbach.CANI_UNDERLYING
   FOR EACH ROW
BEGIN
   
    SELECT CANI_UNDERLYING_SEQ.NEXTVAL INTO :NEW.CANC_UNDRLYG_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."CANI_UNDERLYING_TRIG" ENABLE;
