
  CREATE TABLE "ESBACH"."CANI_SUPPLEMENTARY_DATA" 
   (	"CANC_SUPPLEMENTARY_DATA_ID" NUMBER NOT NULL ENABLE, 
	"CANC_ASSIGNMENT_ID_SUPP_FK" NUMBER, 
	"PLACE_NAME" VARCHAR2(350 CHAR), 
	"ENV_BATCH_SRC" VARCHAR2(40 CHAR), 
	 PRIMARY KEY ("CANC_SUPPLEMENTARY_DATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("CANC_ASSIGNMENT_ID_SUPP_FK")
	  REFERENCES "ESBACH"."CANI_ASSIGNMENT" ("CANC_ASSIGNMENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
     CREATE SEQUENCE  "ESBACH"."CANI_SUPP_DATA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7001 CACHE 500 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."CANI_SUPPLEMENTARY_DATA_TRIG" 
   before INSERT
   ON esbach.CANI_SUPPLEMENTARY_DATA
   FOR EACH ROW
BEGIN
   
   SELECT CANI_SUPP_DATA_SEQ.NEXTVAL INTO :NEW.CANC_SUPPLEMENTARY_DATA_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."CANI_SUPPLEMENTARY_DATA_TRIG" ENABLE;
