drop table "ESBACH"."CANO_REVO_RETO_GRPHDR_INFO" 
  CREATE TABLE "ESBACH"."CANO_REVO_RETO_GRPHDR_INFO" 
   (	"GRP_MSG_MODE" VARCHAR2(20 BYTE), 
	"GRP_CHANNEL" VARCHAR2(20 BYTE), 
	"GRP_BATCH_REF" VARCHAR2(20 BYTE), 
	"GRP_ORGIN_BATCH" VARCHAR2(20 BYTE), 
	"GRP_REASON" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CHL_BTCH_REF" VARCHAR2(32 BYTE), 
	"MSG_RCV_TIMESTAMP" VARCHAR2(40 BYTE), 
	"GRP_HEADER_ID" NUMBER NOT NULL ENABLE, 
	"MSG_ID" VARCHAR2(30 BYTE), 
	"CBO_STATUS" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(300 BYTE), 
	 CONSTRAINT "CANO_REVO_RETO_GRPHDR_INFO_PK" PRIMARY KEY ("GRP_HEADER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  
  
   CREATE SEQUENCE  "ESBACH"."CANO_REVO_RETO_GRPHDR_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11181 CACHE 500 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."CANO_REVO_RETO_GRPHDR_INFO_TRG" 
BEFORE INSERT ON CANO_REVO_RETO_GRPHDR_INFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.GRP_HEADER_ID IS NULL THEN
      SELECT CANO_REVO_RETO_GRPHDR_INFO_SEQ.NEXTVAL INTO :NEW.GRP_HEADER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ESBACH"."CANO_REVO_RETO_GRPHDR_INFO_TRG" ENABLE;
