
  
drop table "ESBACH"."CANO_REVO_RETO_TXN_INFO" 



CREATE TABLE "ESBACH"."CANO_REVO_RETO_TXN_INFO" 
   (	"CAN_REV_RET_TXN_INF_ID" NUMBER NOT NULL ENABLE, 
	"GRP_HDR_ID_TXN_INFO_FK" NUMBER, 
	"TXN_RCVD_BY" VARCHAR2(40 CHAR), 
	"USER_REF" VARCHAR2(40 CHAR), 
	"TRAN_REF" VARCHAR2(40 CHAR), 
	"END_TO_END_ID" VARCHAR2(48 CHAR), 
	"ORIGIN_END_TO_END_ID" VARCHAR2(40 CHAR), 
	"TXN_REASON" VARCHAR2(100 CHAR), 
	"TXN_FOUND" VARCHAR2(40 CHAR), 
	"ORIG_MSG_ID" VARCHAR2(40 CHAR), 
	"ORIG_TXN_ID" VARCHAR2(40 CHAR), 
	"CREDITOR_BANK_BICFI" VARCHAR2(40 CHAR), 
	"CREDITOR_ACC_NO" VARCHAR2(40 CHAR), 
	"TXN_AMOUNT" NUMBER, 
	"CBS_TRAN_REF" VARCHAR2(40 BYTE), 
	"CBS_PAY_REF" VARCHAR2(40 BYTE), 
	"STATUS" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"EXEC_DESC" VARCHAR2(2000 CHAR), 
	"OPTIONAL_ID" VARCHAR2(40 CHAR), 
	"MSG_ID" VARCHAR2(40 CHAR), 
	"TXN_ID" VARCHAR2(40 CHAR), 
	"DEBTOR_BANK_BICFI" VARCHAR2(40 CHAR), 
	"DEBTOR_ACC_NO" VARCHAR2(40 CHAR), 
	"CBS_FAULT_CODE" VARCHAR2(40 BYTE), 
	"CBS_FAULT_STRING" VARCHAR2(50 BYTE), 
	"CBS_REQUEST" CLOB, 
	"FAULT_CODE" VARCHAR2(40 BYTE), 
	"FAULT_STRING" VARCHAR2(100 BYTE), 
	"CBO_STATUS" VARCHAR2(40 BYTE), 
	 CONSTRAINT "CANO_REVO_RETO_TXN_INFO_PK" PRIMARY KEY ("CAN_REV_RET_TXN_INF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CBS_REQUEST") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
  
   CREATE SEQUENCE  "ESBACH"."CANO_REVO_RETO_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6903 CACHE 500 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."CANO_REVO_RETO_TXN_INFO_TRG" 
   before INSERT
   ON ESBACH.CANO_REVO_RETO_TXN_INFO
   FOR EACH ROW
BEGIN  
   SELECT CANO_REVO_RETO_TXN_INFO_SEQ.NEXTVAL INTO :NEW.CAN_REV_RET_TXN_INF_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."CANO_REVO_RETO_TXN_INFO_TRG" ENABLE;


commit
