
  CREATE TABLE "ESBACH"."DC_CONFIG_VALUES" 
   (	"DC_CONFIG_ID" NUMBER, 
	"STML_MTHD" VARCHAR2(4 BYTE), 
	"CLRSYS_PRPRTRY" VARCHAR2(3 BYTE), 
	"INSTAGT_FN_BICFI" VARCHAR2(10 BYTE), 
	"CHRG_BEARER" VARCHAR2(4 BYTE), 
	"SCHMA_NM_PRPRTRY" VARCHAR2(16 BYTE), 
	"DBTR_ACCNO_TYPE" VARCHAR2(8 BYTE), 
	"DBTRAGT_FN_BICFI" VARCHAR2(10 BYTE), 
	"CDTR_ACCNO_TYPE" VARCHAR2(8 BYTE), 
	"SUPP_PLCNAME" VARCHAR2(20 BYTE), 
	"DC_STLMNT_ACC" VARCHAR2(30 CHAR), 
	"DD_STLMNT_ACC" VARCHAR2(30 CHAR), 
	"ACH_DC_IFSC" VARCHAR2(10 CHAR), 
	"BANK_PREFIX" VARCHAR2(10 BYTE), 
	"PMTINFO_CTPURP_PRTRY" VARCHAR2(10 BYTE), 
	"MAX_NO_OF_TXNS" NUMBER(5,0), 
	"MAX_TOTAL_AMOUNT" NUMBER(18,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
