
  CREATE TABLE "ESBACH"."DC_DD_STATUS_INFO" 
   (	"DC_DD_STATUS_INF_ID" NUMBER NOT NULL ENABLE, 
	"TXN_END_TO_END_ID" VARCHAR2(48 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"STATUS_UPDATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"TXN_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DC_DD_STATUS_INFO_PK" PRIMARY KEY ("DC_DD_STATUS_INF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
   CREATE SEQUENCE  "ESBACH"."DC_DD_STATUS_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21394 CACHE 500 NOORDER  NOCYCLE ;

  
  
  CREATE OR REPLACE TRIGGER "ESBACH"."DC_DD_STATUS_INFO_TRG" 
   before INSERT
   ON esbach.DC_DD_STATUS_INFO
   FOR EACH ROW
BEGIN
  
   
   SELECT DC_DD_STATUS_INFO_SEQ.NEXTVAL INTO :NEW.DC_DD_STATUS_INF_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."DC_DD_STATUS_INFO_TRG" ENABLE;
