
 


delete from DCO_TXN_INFO
delete from DCO_GROUP_HEADER_INFO



CREATE TABLE "ESBACH"."DCO_TXN_INFO" 
   (	"DCO_TXN_INF_ID" NUMBER, 
	"DCO_GRP_HDR_ID_TXN_INFO_FK" NUMBER NOT NULL ENABLE, 
	"TXN_REF" VARCHAR2(16 CHAR), 
	"USER_REF" VARCHAR2(35 CHAR), 
	"AMOUNT" NUMBER(18,5), 
	"BENEF_BANK" VARCHAR2(35 CHAR), 
	"BENEF_ACC" VARCHAR2(30 CHAR), 
	"BENEF_NAME" VARCHAR2(140 CHAR), 
	"BENEF_ID" VARCHAR2(35 CHAR), 
	"BENEF_ID_TYPE" VARCHAR2(35 CHAR), 
	"PURP_OF_TRANSFER" VARCHAR2(10 CHAR), 
	"DETAILS_OF_PMTS" VARCHAR2(140 CHAR), 
	"STATUS" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"CBS_TRAN_REF" VARCHAR2(40 CHAR), 
	"CBS_PAY_REF" VARCHAR2(40 CHAR), 
	"EXEC_DESC" VARCHAR2(2000 CHAR), 
	"END_TO_END_ID" VARCHAR2(48 CHAR), 
	"MSG_ID" VARCHAR2(25 CHAR), 
	"TXN_ID" VARCHAR2(25 CHAR), 
	"CBO_GRP_STATUS" VARCHAR2(40 BYTE), 
	"FAULT_CODE" VARCHAR2(40 BYTE), 
	"FAULT_STRING" VARCHAR2(100 BYTE), 
	"CBO_TXN_STATUS" VARCHAR2(40 BYTE), 
	"CBS_REQUEST_MESSAGE" CLOB, 
	 CONSTRAINT "DCO_TXN_INFO_PK" PRIMARY KEY ("DCO_TXN_INF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "DCO_GRP_HDR_ID_TXN_INFO_FK" FOREIGN KEY ("DCO_GRP_HDR_ID_TXN_INFO_FK")
	  REFERENCES "ESBACH"."DCO_GROUP_HEADER_INFO" ("DCO_GRP_HEADER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CBS_REQUEST_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
   CREATE SEQUENCE  "ESBACH"."DCO_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20094 CACHE 20 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."DCO_TXN_INFO_TRG" 
   before INSERT
   ON ESBACH.DCO_TXN_INFO
   FOR EACH ROW
BEGIN
  
   SELECT DCO_TXN_INFO_SEQ.NEXTVAL INTO :NEW.DCO_TXN_INF_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."DCO_TXN_INFO_TRG" ENABLE;
