
drop table "ESBACH"."DCO_GROUP_HEADER_INFO" ;  


CREATE TABLE "ESBACH"."DCO_GROUP_HEADER_INFO" 
   (	"DCO_GRP_HEADER_ID" NUMBER, 
	"CHANNEL" VARCHAR2(16 CHAR), 
	"PRIORITY1" NUMBER(3,0), 
	"BATCH_REFERENCE" VARCHAR2(16 CHAR), 
	"ORDERING_CUSTOMER_ACCOUNT" VARCHAR2(30 CHAR), 
	"ORDERING_CUSTOMER_NAME" VARCHAR2(140 BYTE), 
	"ORDERING_CUSTOMER_ID" VARCHAR2(35 CHAR), 
	"ORDERING_CUSTOMER_ID_TYPE" VARCHAR2(35 CHAR), 
	"PURPOSE_OF_TRANSFER" VARCHAR2(3 CHAR), 
	"CURRENCY" VARCHAR2(3 CHAR), 
	"STATUS" VARCHAR2(60 BYTE), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"MSG_RCV_TIMESTAMP" VARCHAR2(40 BYTE), 
	"OPTIONAL_ID" VARCHAR2(20 CHAR), 
	"CHL_BTCH_REF" VARCHAR2(32 CHAR), 
	"MSG_CHANNEL_TO_ESB" CLOB, 
	"CBS_TRAN_REF" VARCHAR2(40 BYTE), 
	"CBS_PAY_REF" VARCHAR2(30 BYTE), 
	"FAULT_CODE" VARCHAR2(40 BYTE), 
	"FAULT_STRING" VARCHAR2(100 BYTE), 
	"CBS_REQUEST_MESSAGE" CLOB, 
	"MSG_ESB_TO_CBO" CLOB, 
	"MSG_CBO_TO_ESB" CLOB, 
	 CONSTRAINT "DCO_GRP_HEADER_INFO_PK" PRIMARY KEY ("DCO_GRP_HEADER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MSG_CHANNEL_TO_ESB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CBS_REQUEST_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MSG_ESB_TO_CBO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MSG_CBO_TO_ESB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
   CREATE SEQUENCE  "ESBACH"."DCO_GROUP_HEADER_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6868 CACHE 20 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."DCO_GROUP_HEADER_INFO_TRG" 
   before INSERT
   ON ESBACH.DCO_GROUP_HEADER_INFO
   FOR EACH ROW
BEGIN
  
   SELECT DCO_GROUP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.DCO_GRP_HEADER_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."DCO_GROUP_HEADER_INFO_TRG" ENABLE;

commit

