


drop table "ESBACH"."DDO_GROUP_HEADER_INFO" 


  CREATE TABLE "ESBACH"."DDO_GROUP_HEADER_INFO" 
   (	"DDO_GRP_HEADER_ID" NUMBER, 
	"MSG_RCV_TIMESTAMP" VARCHAR2(50 BYTE), 
	"CHANNEL" VARCHAR2(16 CHAR), 
	"PRIORITY" NUMBER(3,0), 
	"BATCH_REFERENCE" VARCHAR2(16 CHAR), 
	"ORDERING_CUSTOMER_ACCOUNT" VARCHAR2(30 CHAR), 
	"ORDERING_CUSTOMER_NAME" VARCHAR2(140 CHAR), 
	"ORDERING_CUSTOMER_ID" VARCHAR2(35 CHAR), 
	"ORDERING_CUSTOMER_ID_TYPE" VARCHAR2(35 CHAR), 
	"PURPOSE_OF_TRANSFER" VARCHAR2(10 CHAR), 
	"CURRENCY" VARCHAR2(3 CHAR), 
	"STATUS" VARCHAR2(35 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"CHL_BATCH_REF" VARCHAR2(30 BYTE), 
	"OPT_ID" VARCHAR2(10 CHAR), 
	"CBO_STATUS" VARCHAR2(40 BYTE), 
	"MSG_CHANNEL_TO_ESB" CLOB, 
	"MSG_ESB_TO_CBO" CLOB, 
	"MSG_CBO_TO_ESB" CLOB, 
	 CONSTRAINT "DD_GRP_HEADER_INFO_PK" PRIMARY KEY ("DDO_GRP_HEADER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MSG_CHANNEL_TO_ESB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MSG_ESB_TO_CBO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MSG_CBO_TO_ESB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
   CREATE SEQUENCE  "ESBACH"."DDO_GROUP_HEADER_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9055 CACHE 500 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."DDO_GROUP_HEADER_INFO_TRG" 
   before INSERT
   ON esbach.DDO_GROUP_HEADER_INFO
   FOR EACH ROW
BEGIN
  
   
   SELECT DDO_GROUP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.DDO_GRP_HEADER_ID FROM SYS.DUAL;
END;
commit
/
ALTER TRIGGER "ESBACH"."DDO_GROUP_HEADER_INFO_TRG" ENABLE;
