

drop table "ESBACH"."DDO_TXN_INFO" ;







  CREATE TABLE "ESBACH"."DDO_TXN_INFO" 
   (	"DDO_TXN_INF_ID" NUMBER, 
	"DDO_GRP_HDR_ID_TXN_INFO_FK" NUMBER NOT NULL ENABLE, 
	"TXN_REF" VARCHAR2(16 CHAR), 
	"END_TO_END_ID" VARCHAR2(35 CHAR), 
	"USER_REF" VARCHAR2(35 CHAR), 
	"MANDATEID" VARCHAR2(20 BYTE), 
	"MANDATE_FIRST_COLLECTION_DATE" DATE, 
	"MANDATE_PAY_COLLECTION_DATE" VARCHAR2(20 CHAR), 
	"MANDATE_PAY_SEQUENCE" NUMBER, 
	"AMOUNT" NUMBER(18,5), 
	"PAYER_BANK" VARCHAR2(35 CHAR), 
	"PAYER_ACCOUNT" VARCHAR2(30 CHAR), 
	"PAYER_NAME" VARCHAR2(140 CHAR), 
	"PAYER_ID" VARCHAR2(35 CHAR), 
	"PAYER_ID_TYPE" VARCHAR2(35 CHAR), 
	"PURP_OF_TRANSFER" VARCHAR2(20 BYTE), 
	"DETAILS_OF_PMTS" VARCHAR2(140 CHAR), 
	"STATUS" VARCHAR2(35 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"CBS_TRAN_REF" VARCHAR2(40 CHAR), 
	"CBS_PAY_REF" VARCHAR2(40 CHAR), 
	"EXEC_DESC" VARCHAR2(2000 CHAR), 
	"IIB_STATUS" VARCHAR2(4 BYTE), 
	"MSG_ID" VARCHAR2(20 BYTE), 
	"TXN_ID" VARCHAR2(20 BYTE), 
	"PMT_ID_TXN_ID" VARCHAR2(40 BYTE), 
	"DBTRACCT_ID_IBAN" VARCHAR2(40 BYTE), 
	"CBO_STATUS" VARCHAR2(40 BYTE), 
	"CBS_REQUEST_MESSAGE" CLOB, 
	"FAULT_CODE" VARCHAR2(30 BYTE), 
	"FAULT_STRING" VARCHAR2(60 BYTE), 
	 CONSTRAINT "DD_TXN_INFO_PK" PRIMARY KEY ("DDO_TXN_INF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "DD_GRP_HDR_ID_TXN_INFO_FK" FOREIGN KEY ("DDO_GRP_HDR_ID_TXN_INFO_FK")
	  REFERENCES "ESBACH"."DDO_GROUP_HEADER_INFO" ("DDO_GRP_HEADER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CBS_REQUEST_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
  CREATE SEQUENCE  "ESBACH"."DDO_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9671 CACHE 500 NOORDER  NOCYCLE ;
  
  

  CREATE OR REPLACE TRIGGER "ESBACH"."DDO_TXN_INFO_TRG" 
   before INSERT
   ON esbach.DDO_TXN_INFO
   FOR EACH ROW
BEGIN
  
   
   SELECT DDO_TXN_INFO_SEQ.NEXTVAL INTO :NEW.DDO_TXN_INF_ID FROM SYS.DUAL;
END;
commit
/
ALTER TRIGGER "ESBACH"."DDO_TXN_INFO_TRG" ENABLE;
