


drop table "ESBACH"."MANDATE_MGMT_INFO"  


  CREATE TABLE "ESBACH"."MANDATE_MGMT_INFO" 
   (	"MND_GP_HDR_ID" NUMBER NOT NULL ENABLE, 
	"MI_REFERENCE" VARCHAR2(35 CHAR), 
	"MND_GP_HDR_CRE_DT_TM" DATE, 
	"LCLINSTRMT_CD" VARCHAR2(35 CHAR), 
	"RECURRINGFREQUENCY" VARCHAR2(4 CHAR), 
	"FREQUENCY" VARCHAR2(4 CHAR), 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"COLLECTIONAMT" NUMBER(13,5), 
	"MAXIMUMAMT" NUMBER(13,5), 
	"MNDT_REASON" VARCHAR2(35 CHAR), 
	"CDTR_NAME" VARCHAR2(140 CHAR), 
	"CDTR_IDTYPE" VARCHAR2(35 CHAR), 
	"CDTR_ID" VARCHAR2(35 CHAR), 
	"CDTR_ACCOUNT" VARCHAR2(34 CHAR), 
	"CDTR_BICFI" VARCHAR2(11 CHAR), 
	"CDTR_BRNCHID" VARCHAR2(35 CHAR), 
	"DBTR_NAME" VARCHAR2(140 CHAR), 
	"DBTR_ID" VARCHAR2(35 CHAR), 
	"DBTR_IDTYPE" VARCHAR2(35 CHAR), 
	"DBTR_ACCOUNT" VARCHAR2(34 CHAR), 
	"DBTR_BICFI" VARCHAR2(11 CHAR), 
	"DBTR_BRNCHID" VARCHAR2(35 CHAR), 
	"RFRDDOC_NB" VARCHAR2(400 CHAR), 
	"MI_MA_SPLDT_ENVP_IRREVOCABLE" VARCHAR2(11 CHAR), 
	"MI_MA_SPLDT_ENVP_INITBY" VARCHAR2(8 CHAR), 
	"MI_MA_SPLDT_ENVP_AUTOPOSTPAY" VARCHAR2(5 CHAR), 
	"MI_MA_SPLDT_ENVP_RCURFRQCY" NUMBER(2,0), 
	"MI_MA_SPLDT_ENVP_PRSNTEACH" VARCHAR2(400 CHAR), 
	"MI_MA_SPLDT_ENVP_NMPYMTS" NUMBER(3,0), 
	"MI_MA_SPLDT_ENVP_TXPURP" VARCHAR2(35 CHAR), 
	"MND_SPLDT_ENVP_ATCMT_FNAME" VARCHAR2(255 CHAR), 
	"MND_SPLDT_ENVP_ATCMT_FSIZE" NUMBER(19,0), 
	"MND_SPLDT_ENVP_ATCMT_FDATA" BLOB, 
	"MND_SPLDT_ENVP_ATCMT_FTYPE" VARCHAR2(255 CHAR), 
	"MND_SPLDT_ENVP_ATCMT_FCMT" VARCHAR2(255 CHAR), 
	"MI_STATUS" VARCHAR2(100 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"MA_STATUS" VARCHAR2(100 CHAR), 
	"MT_STATUS" VARCHAR2(100 CHAR), 
	"MA_REFERENCE" VARCHAR2(35 BYTE), 
	"MT_REFERENCE" VARCHAR2(35 BYTE), 
	"MA_REASON" VARCHAR2(40 BYTE), 
	"MT_REASON" VARCHAR2(40 BYTE), 
	"MND_GP_HDP_MSGID" VARCHAR2(40 CHAR), 
	"STATUS" VARCHAR2(40 BYTE), 
	 PRIMARY KEY ("MND_GP_HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MND_SPLDT_ENVP_ATCMT_FDATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  
   CREATE SEQUENCE  "ESBACH"."MANDATE_MGMT_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6501 CACHE 500 NOORDER  NOCYCLE ;

  
  
  CREATE OR REPLACE TRIGGER "ESBACH"."MANDATE_MGMT_INFO_TRG" 
BEFORE INSERT ON esbach.MANDATE_MGMT_INFO 
FOR EACH ROW
BEGIN
  
      SELECT MANDATE_MGMT_INFO_SEQ.NEXTVAL INTO :NEW.MND_GP_HDR_ID FROM SYS.DUAL;
    
END;
/
ALTER TRIGGER "ESBACH"."MANDATE_MGMT_INFO_TRG" ENABLE;


commit
