
drop table  "ESBACH"."MANDATE_MGMT_INFO_INWARD" 

CREATE TABLE "ESBACH"."MANDATE_MGMT_INFO_INWARD" 
   (	"MND_GP_HDR_ID" NUMBER NOT NULL ENABLE, 
	"MND_GP_HDR_MSGID" VARCHAR2(35 CHAR), 
	"MND_GP_HDR_CRE_DT_TM" VARCHAR2(30 BYTE), 
	"MNDT_REQID" VARCHAR2(20 CHAR), 
	"RSN_PRTRY" VARCHAR2(35 CHAR), 
	"MNDTAM_RSN_PRTRY" VARCHAR2(35 CHAR), 
	"MNDTAM_LCLINSTRMT_CD" VARCHAR2(35 CHAR), 
	"MNDTAM_MNDTID" VARCHAR2(20 CHAR), 
	"MNDTAM_ADDTLINF" VARCHAR2(105 CHAR), 
	"OCURNCS_SEQTYPE" VARCHAR2(4 CHAR), 
	"OCURNCS_FRQCY_TYPE" VARCHAR2(4 CHAR), 
	"OCURNCS_DRTN_FROMDATE" DATE, 
	"OCURNCS_DRTN_TODATE" DATE, 
	"MNDT_COLLCTNAMT" NUMBER(13,5), 
	"MNDT_MAXAMT" NUMBER(13,5), 
	"MNDTTR_RSN_PRTRY" VARCHAR2(35 CHAR), 
	"CDTR_NAME" VARCHAR2(140 CHAR), 
	"CDTR_ID_PRVTID_OTHR_ID" VARCHAR2(35 CHAR), 
	"CDTR_ID_SCHMENM_PRTRY" VARCHAR2(35 CHAR), 
	"CDTRACCT_ID_OTHR_ID" VARCHAR2(34 CHAR), 
	"CDTRAGT_FINID_BICFI" VARCHAR2(11 CHAR), 
	"CDTRAGT_BRNCHID_ID" VARCHAR2(35 CHAR), 
	"DBTR_NAME" VARCHAR2(140 CHAR), 
	"DBTR_ID_PRVTID_OTHR_ID" VARCHAR2(35 CHAR), 
	"DBTR_ID_SCHMENM_PRTRY" VARCHAR2(35 CHAR), 
	"DBTRACCT_ID_OTHR_ID" VARCHAR2(34 CHAR), 
	"DBTRAGT_FINID_BICFI" VARCHAR2(11 CHAR), 
	"DBTRAGT_BRNCHID_ID" VARCHAR2(35 CHAR), 
	"MNDTAM_ORGNLMNDTID" VARCHAR2(35 CHAR), 
	"MNDTTR_ORGNLMNDTID" VARCHAR2(20 CHAR), 
	"RFRDDOC_NB" VARCHAR2(400 CHAR), 
	"SPLDT_ENVP_IRREVOCABLE" VARCHAR2(11 CHAR), 
	"SPLDT_ENVP_INITBY" VARCHAR2(8 CHAR), 
	"SPLDT_ENVP_AUTOPOSTPAY" VARCHAR2(5 CHAR), 
	"SPLDT_ENVP_RCURFRQCY" NUMBER(2,0), 
	"SPLDT_ENVP_PRSNTEACH" VARCHAR2(400 CHAR), 
	"SPLDT_ENVP_NMPYMTS" NUMBER(3,0), 
	"SPLDT_ENVP_TXPURP" VARCHAR2(35 CHAR), 
	"SPLDT_ENVP_ATCMT_FNAME" VARCHAR2(255 CHAR), 
	"SPLDT_ENVP_ATCMT_FSIZE" NUMBER(19,0), 
	"SPLDT_ENVP_ATCMT_FDATA" BLOB, 
	"SPLDT_ENVP_ATCMT_FTYPE" VARCHAR2(255 CHAR), 
	"SPLDT_ENVP_ATCMT_FCMT" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"MND_INTERFACE_CODE" VARCHAR2(32 CHAR), 
	"MNDTTR_RSN_ADDTINF" VARCHAR2(105 CHAR), 
	"MNDTAM_ID" VARCHAR2(20 CHAR), 
	"MNDTTR_ID" VARCHAR2(50 CHAR), 
	"MSG_ID" VARCHAR2(40 BYTE), 
	"CURRENCY" VARCHAR2(3 BYTE), 
	"DBTRACCT_ID_IBAN_ID" VARCHAR2(35 BYTE), 
	"CDTRACCT_ID_IBAN_ID" VARCHAR2(35 BYTE), 
	 CONSTRAINT "MANDATE_MGMT_INFO_INWARD_PK" PRIMARY KEY ("MND_GP_HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SPLDT_ENVP_ATCMT_FDATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  
  
   CREATE SEQUENCE  "ESBACH"."MANDATE_MGMT_INFO_INWARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6501 CACHE 500 NOORDER  NOCYCLE ;

  
  
  
  CREATE OR REPLACE TRIGGER "ESBACH"."MANDATE_MGMT_INFO_INWARD_TRG" 
   before INSERT
   ON ESBACH.MANDATE_MGMT_INFO_INWARD
   FOR EACH ROW
BEGIN
   SELECT MANDATE_MGMT_INFO_INWARD_SEQ.NEXTVAL INTO :NEW.MND_GP_HDR_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."MANDATE_MGMT_INFO_INWARD_TRG" ENABLE;



commit
