
 
drop table "ESBACH"."PRI_GP_HEADER_INFO" 

CREATE TABLE "ESBACH"."PRI_GP_HEADER_INFO" 
   (	"PR_GP_HEADER_ID" NUMBER NOT NULL ENABLE, 
	"MSG_ID" VARCHAR2(16 CHAR), 
	"CRE_DT_TM" VARCHAR2(40 BYTE), 
	"NB_OF_TXS" NUMBER(*,0), 
	"TTL_RTRD_INTR_BK_STTLM_AMT" NUMBER(18,5), 
	"INTR_BK_STTLM_DT" DATE, 
	"STTLM_INF_STTLMN_MTD" VARCHAR2(35 CHAR) DEFAULT 'CLRG' NOT NULL ENABLE, 
	"STTLM_INF_CLR_SYS_PRTRY" VARCHAR2(35 CHAR) DEFAULT 'CBO' NOT NULL ENABLE, 
	"INSTG_AGT_FIN_INSTN_ID_BICFI" VARCHAR2(35 CHAR), 
	"INSTG_AGT_BRNCH_ID_ID" VARCHAR2(35 CHAR), 
	"INSTD_AGT_FIN_INSTN_ID_BICFI" VARCHAR2(35 CHAR), 
	"INSTD_AGT_BRNCH_ID_ID" VARCHAR2(35 CHAR), 
	"SOURCE_SYS_CODE" VARCHAR2(35 CHAR), 
	"SOURCE_SYS_ID" VARCHAR2(35 CHAR), 
	"GROUPRTR_STATUS" VARCHAR2(20 CHAR), 
	"SRC_MSG" CLOB, 
	 PRIMARY KEY ("PR_GP_HEADER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SRC_MSG") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
  
   CREATE SEQUENCE  "ESBACH"."PRI_GP_HEADER_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6501 CACHE 500 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "ESBACH"."PRI_GP_HEADER_INFO_TRIG" 
BEFORE INSERT ON esbach.PRI_GP_HEADER_INFO 
FOR EACH ROW
BEGIN
   
      SELECT PRI_GP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.PR_GP_HEADER_ID FROM SYS.DUAL;
    
END;
/
ALTER TRIGGER "ESBACH"."PRI_GP_HEADER_INFO_TRIG" ENABLE;
