
 

drop table "ESBACH"."PRI_TXN_INFO" 
CREATE TABLE "ESBACH"."PRI_TXN_INFO" 
   (	"PR_TXN_INFO_ID" NUMBER NOT NULL ENABLE, 
	"PR_GP_HEADER_ID_TXN_FK" NUMBER, 
	"RTR_ID" VARCHAR2(16 CHAR), 
	"ORGNL_TX_ID" VARCHAR2(16 CHAR), 
	"RTRD_INTR_BK_STTLM_AMT" NUMBER(*,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CBS_TRAN_REF" VARCHAR2(100 CHAR), 
	"ACCOUNT" VARCHAR2(30 CHAR), 
	"EXEC_DESC" VARCHAR2(2000 CHAR), 
	"CBS_PAY_REF" VARCHAR2(100 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"MSG_ID" VARCHAR2(50 BYTE), 
	"CBS_REQUEST" CLOB, 
	"FAULT_CODE" VARCHAR2(30 BYTE), 
	"FAULT_STRING" VARCHAR2(60 BYTE), 
	 PRIMARY KEY ("PR_TXN_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CBS_REQUEST") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  
  CREATE SEQUENCE  "ESBACH"."PRI_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6501 CACHE 500 NOORDER  NOCYCLE ;

  
  CREATE OR REPLACE TRIGGER "ESBACH"."PRI_TXN_INFO_TRIG" 
BEFORE INSERT ON esbach.PRI_TXN_INFO 
FOR EACH ROW
BEGIN
   
      SELECT PRI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.PR_TXN_INFO_ID FROM SYS.DUAL;
    
END;
/
ALTER TRIGGER "ESBACH"."PRI_TXN_INFO_TRIG" ENABLE;


commit