
  
drop table "ESBACH"."REVI_TXN_INFO" 

CREATE TABLE "ESBACH"."REVI_TXN_INFO" 
   (	"REV_TXN_INF_ID" NUMBER NOT NULL ENABLE, 
	"REV_GRP_HDR_ID_TXN_INFO_FK" NUMBER, 
	"RVSL_ID" VARCHAR2(16 CHAR), 
	"ORGNL_TX_ID" VARCHAR2(16 CHAR), 
	"RVSD_INTRBK_STTLM_AMT" NUMBER(18,5), 
	"STATUS" VARCHAR2(40 CHAR), 
	"CBS_TRAN_REF" VARCHAR2(25 CHAR), 
	"ACCOUNT" VARCHAR2(30 CHAR), 
	"EXEC_DESC" VARCHAR2(2000 CHAR), 
	"CBS_PAY_REF" VARCHAR2(35 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"MSG_ID" VARCHAR2(40 BYTE), 
	"CBS_REQUEST_MESSAGE" CLOB, 
	"FAULT_CODE" VARCHAR2(20 BYTE), 
	"FAULT_STRING" VARCHAR2(20 BYTE), 
	"TXN_FOUND" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("REV_TXN_INF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("REV_GRP_HDR_ID_TXN_INFO_FK")
	  REFERENCES "ESBACH"."REVI_GRP_HEADER_INFO" ("REV_GRP_HEADER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CBS_REQUEST_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

     CREATE SEQUENCE  "ESBACH"."REVI_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6508 CACHE 500 NOORDER  NOCYCLE ;

  
  
  CREATE OR REPLACE TRIGGER "ESBACH"."REVI_TXN_INFO_TRIG" 
   before INSERT
   ON esbach.REVI_TXN_INFO
   FOR EACH ROW
BEGIN
    
    SELECT REVI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.REV_TXN_INF_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."REVI_TXN_INFO_TRIG" ENABLE;



commit
