SELECT * FROM DCO_GROUP_HEADER_INFO;
SELECT * FROM DCO_TXN_INFO;
SELECT * FROM DC_DD_STATUS_INFO;

SELECT * FROM DCI_TXN_INFO;
SELECT * FROM DCI_GP_HEADER_INFO;

SELECT * FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '3101170222000043';
SELECT * FROM DCO_TXN_INFO WHERE DCO_GRP_HDR_ID_TXN_INFO_FK = (SELECT DCO_GRP_HEADER_ID FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '3101170222000043');
SELECT * FROM DC_DD_STATUS_INFO WHERE TXN_END_TO_END_ID IN (SELECT END_TO_END_ID FROM DCO_TXN_INFO WHERE DCO_GRP_HDR_ID_TXN_INFO_FK = (SELECT DCO_GRP_HEADER_ID FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '3101170222000036'));

DELETE FROM DC_DD_STATUS_INFO WHERE TXN_END_TO_END_ID IN (SELECT END_TO_END_ID FROM DCO_TXN_INFO WHERE DCO_GRP_HDR_ID_TXN_INFO_FK = (SELECT DCO_GRP_HEADER_ID FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '3101170222000036'));
DELETE FROM DCO_TXN_INFO WHERE DCO_GRP_HDR_ID_TXN_INFO_FK = (SELECT DCO_GRP_HEADER_ID FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '3101170222000036');
DELETE FROM DCO_GROUP_HEADER_INFO WHERE BATCH_REFERENCE LIKE '3101170222000036';




DELETE FROM DC_DD_STATUS_INFO;
DELETE FROM DCO_TXN_INFO;
DELETE FROM DCO_GROUP_HEADER_INFO;


DELETE FROM DCI_TXN_INFO;
DELETE FROM DCI_GP_HEADER_INFO;

select COUNT(*) from DCO_TXN_INFO;

Alter table DCO_GROUP_HEADER_INFO MODIFY PRIORITY1 VARCHAR2(4);


ALTER TABLE esbach.dci_txn_info add
   (
      txn_id        varchar2(25 char),
      CBO_GRP_STATUS	VARCHAR2(40),
      CBO_TXN_STATUS	VARCHAR2(40)
      
   );
   
   ALTER TABLE esbach.ddi_txn_info add
   (
      txn_id        varchar2(25 char),
      CBO_GRP_STATUS	VARCHAR2(40),
      CBO_TXN_STATUS	VARCHAR2(40)
      
   );
   
   ALTER TABLE esbach.revi_txn_info add
   (
      txn_id        varchar2(25 char),
      CBO_GRP_STATUS	VARCHAR2(40),
      CBO_TXN_STATUS	VARCHAR2(40)
      
   );
   
   ALTER TABLE esbach.pri_txn_info add
   (
      txn_id        varchar2(25 char),
      CBO_GRP_STATUS	VARCHAR2(40),
      CBO_TXN_STATUS	VARCHAR2(40)
      
   );
   
   ALTER TABLE esbach.cani_txn_info add
   (
      txn_id        varchar2(25 char),
      CBO_GRP_STATUS	VARCHAR2(40),
      CBO_TXN_STATUS	VARCHAR2(40)
      
   );
   commit



