
drop table "ESBACH"."WPS_ADD_OPS_INFO" 


CREATE TABLE "ESBACH"."WPS_ADD_OPS_INFO" 
   (	"WPS_ADD_OPS_INFO_ID" NUMBER NOT NULL ENABLE, 
	"ADDOPS_FILE_NAME" VARCHAR2(50 CHAR), 
	"EMPLOYER_NUM_TYPE" VARCHAR2(3 CHAR), 
	"EMPLOYER_CR_NO" VARCHAR2(20 CHAR), 
	"PAYER_NUMBER_TYPE" VARCHAR2(3 CHAR), 
	"PAYER_CR_NO" VARCHAR2(20 CHAR), 
	"EMPLOYER_NAME" VARCHAR2(70 CHAR), 
	"PAYER_NAME" VARCHAR2(70 CHAR), 
	"PAYER_ACCTNO_IBAN" VARCHAR2(30 CHAR), 
	"PAYER_BNK_SHORT_NAME" VARCHAR2(4 CHAR), 
	"PAYER_BRANCH" VARCHAR2(12 CHAR), 
	"EMPLOYER_TYPE" VARCHAR2(7 CHAR), 
	"EMPLOYER_BIZ_TYPE" VARCHAR2(70 CHAR), 
	"EMPLOYER_BRANCHES_COUNT" VARCHAR2(3 CHAR), 
	"EMPLOYER_GRADE" VARCHAR2(1 CHAR), 
	"EMPLOYER_EMAIL" VARCHAR2(254 CHAR), 
	"EMPLOYER_ADDRESS" VARCHAR2(254 CHAR), 
	"EMPLOYER_PH_NO" VARCHAR2(20 CHAR), 
	"EMPLOYER_POSTAL_CODE" VARCHAR2(14 CHAR), 
	"EMPLOYER_POBOX" VARCHAR2(6 CHAR), 
	"EMPLOYER_SIGNATORY1" VARCHAR2(70 CHAR), 
	"EMPLOYER_SIGNATORY2" VARCHAR2(70 CHAR), 
	"EMPLOYER_SIGNATORY3" VARCHAR2(70 CHAR), 
	"STATUS_CODE" VARCHAR2(20 CHAR), 
	"EXEC_DESC" VARCHAR2(2000 CHAR), 
	"STATUS_TRAIL" VARCHAR2(40 CHAR), 
	"FAILED_RECORD_NO" NUMBER(3,0), 
	 PRIMARY KEY ("WPS_ADD_OPS_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "WPS_ADD_OPS_INFO_UK1" UNIQUE ("ADDOPS_FILE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
   CREATE SEQUENCE  "ESBACH"."WPS_ADD_OPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;

  
  CREATE OR REPLACE TRIGGER "ESBACH"."WPS_ADD_OPS_INFO_TRIG" 
   before INSERT
   ON esbach.WPS_ADD_OPS_INFO
   FOR EACH ROW
BEGIN
   SELECT WPS_ADD_OPS_SEQ.NEXTVAL INTO :NEW.WPS_ADD_OPS_INFO_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."WPS_ADD_OPS_INFO_TRIG" ENABLE;
