
drop table "ESBACH"."WPS_SIF_HEADER_INFO"  


CREATE TABLE "ESBACH"."WPS_SIF_HEADER_INFO" 
   (	"WPS_SIF_HEADER_INFO_ID" NUMBER NOT NULL ENABLE, 
	"SIF_CBO_FILE_NAME" VARCHAR2(200 CHAR), 
	"EMPLOYEER_CRNO" VARCHAR2(20 CHAR), 
	"PAYER_CRNO" VARCHAR2(20 CHAR), 
	"PAYER_BANK_SHORT_NAME" VARCHAR2(4 CHAR), 
	"PAYER_ACCOUNT_NO" VARCHAR2(30 CHAR), 
	"SALARY_YEAR" VARCHAR2(4 CHAR), 
	"SALARY_MONTH" VARCHAR2(2 CHAR), 
	"TOTAL_SALARIES" VARCHAR2(30 CHAR), 
	"NO_OF_RECORDS" VARCHAR2(10 CHAR), 
	"ESB_STATUS" VARCHAR2(100 CHAR), 
	"EXEC_DESC" VARCHAR2(4000 CHAR), 
	"CBS_TXN_REF" VARCHAR2(30 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(20 CHAR), 
	"CBS_PAY_REF" VARCHAR2(20 BYTE), 
	"CBS_FAULT_CODE" VARCHAR2(20 BYTE), 
	"CBS_FAULT_STRING" VARCHAR2(20 BYTE), 
	"CBO_STATUS" VARCHAR2(50 BYTE), 
	"SIF_CHL_FILE_NAME" VARCHAR2(50 BYTE), 
	"SIF_ACK_RESPONSE" CLOB, 
	"REP_ACK_RESPONSE" CLOB, 
	"SYNC_BACK_RESPONSE" CLOB, 
	"ERROR_LIST" VARCHAR2(200 BYTE), 
	"CHL_REFERENCE" VARCHAR2(30 BYTE), 
	"OPTIONALIDENTIFIER" VARCHAR2(20 BYTE), 
	"CBS_REQUEST_MESSAGE" CLOB, 
	 PRIMARY KEY ("WPS_SIF_HEADER_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SIF_ACK_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("REP_ACK_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SYNC_BACK_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CBS_REQUEST_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE SEQUENCE  "ESBACH"."WPS_SIF_HEADER_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 342 CACHE 20 NOORDER  NOCYCLE ;
  
  CREATE OR REPLACE TRIGGER "ESBACH"."WPS_SIF_HEADER_INFO_TRIG" 
   before INSERT
   ON esbach.WPS_SIF_HEADER_INFO
   FOR EACH ROW
BEGIN
   SELECT WPS_SIF_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.WPS_SIF_HEADER_INFO_ID FROM SYS.DUAL;
END;
/
ALTER TRIGGER "ESBACH"."WPS_SIF_HEADER_INFO_TRIG" ENABLE;
