--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."CANI_SUPPLEMENTARY_DATA" (
		"CANC_SUPPLEMENTARY_DATA_ID" NUMBER NOT NULL,
		"CANC_ASSIGNMENT_ID_SUPP_FK" NUMBER,
		"PLACE_NAME" VARCHAR2(350 CHAR),
		"ENV_BATCH_SRC" VARCHAR2(40 CHAR)
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."CANI_SUPPLEMENTARY_DATA" ADD CONSTRAINT "SYS_C0011390" CHECK ("CANC_SUPPLEMENTARY_DATA_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."CANI_SUPPLEMENTARY_DATA" ADD CONSTRAINT "SYS_C0011391" PRIMARY KEY
	("CANC_SUPPLEMENTARY_DATA_ID");

ALTER TABLE "ACHADMIN"."CANI_SUPPLEMENTARY_DATA" ADD CONSTRAINT "SYS_C0011392" FOREIGN KEY
	("CANC_ASSIGNMENT_ID_SUPP_FK")
	REFERENCES "ACHADMIN"."CANI_ASSIGNMENT"
	("CANC_ASSIGNMENT_ID");
	
	CREATE SEQUENCE  "ACHADMIN"."CANI_SUPP_DATA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "ACHADMIN"."CANI_SUPPLEMENTARY_DATA_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."CANI_SUPPLEMENTARY_DATA"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
   SELECT CANI_SUPP_DATA_SEQ.NEXTVAL INTO :NEW.CANC_SUPPLEMENTARY_DATA_ID FROM SYS.DUAL;
END;

COMMIT