--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."CANI_TXN_INFO" (
		"CANC_TXN_INFO_ID" NUMBER NOT NULL,
		"CANC_ASSIGNMENT_ID_TXN_FK" NUMBER,
		"CANC_ID" VARCHAR2(35 CHAR),
		"ORGNL_TX_ID" VARCHAR2(35 CHAR),
		"STATUS" VARCHAR2(50 CHAR),
		"CBS_TRAN_REF" VARCHAR2(40 CHAR),
		"ACC_NUMBER" VARCHAR2(30 CHAR),
		"AMOUNT" NUMBER(18 , 2),
		"STATUS_TRAIL" VARCHAR2(40),
		"CBS_PAY_REF" VARCHAR2(35),
		"EXEC_DESC" VARCHAR2(2000),
		"DESCRIPTION" VARCHAR2(500 CHAR),
		"ASSIGN_ID" VARCHAR2(20 CHAR),
		"FAULT_CODE" VARCHAR2(20),
		"FAULT_STRING" VARCHAR2(500),
		"CBS_REQUEST_MESSAGE" CLOB,
		"TXN_ID" VARCHAR2(25 CHAR),
		"CBO_GRP_STATUS" VARCHAR2(40),
		"CBO_TXN_STATUS" VARCHAR2(150)
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."CANI_TXN_INFO" ADD CONSTRAINT "SYS_C0011538" CHECK ("CANC_TXN_INFO_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."CANI_TXN_INFO" ADD CONSTRAINT "SYS_C0011539" PRIMARY KEY
	("CANC_TXN_INFO_ID");

ALTER TABLE "ACHADMIN"."CANI_TXN_INFO" ADD CONSTRAINT "SYS_C0011540" FOREIGN KEY
	("CANC_ASSIGNMENT_ID_TXN_FK")
	REFERENCES "ACHADMIN"."CANI_ASSIGNMENT"
	("CANC_ASSIGNMENT_ID");
CREATE SEQUENCE  "ACHADMIN"."CANI_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."CANI_TXN_INFO_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."CANI_TXN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
    SELECT CANI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.CANC_TXN_INFO_ID FROM SYS.DUAL;
END;

COMMIT