--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."CANI_UNDERLYING" (
		"CANC_UNDRLYG_ID" NUMBER NOT NULL,
		"CANC_ASSIGNMENT_ID_UNDRLYG_FK" NUMBER,
		"ORG_GP_INF_AND_CANC_GP_CANC_ID" VARCHAR2(35 CHAR),
		"ORG_GP_INF_AND_CANC_ORG_MSG_ID" VARCHAR2(35 CHAR),
		"ORG_GP_INF_AND_CAN_ORG_MGNM_ID" VARCHAR2(35 CHAR),
		"ORG_GP_INF_AND_CANC_NO_OF_TXS" NUMBER,
		"ORG_GP_INF_AND_CANC_GP_CANC" VARCHAR2(10 CHAR)
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."CANI_UNDERLYING" ADD CONSTRAINT "SYS_C0011544" CHECK ("CANC_UNDRLYG_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."CANI_UNDERLYING" ADD CONSTRAINT "SYS_C0011545" PRIMARY KEY
	("CANC_UNDRLYG_ID");

ALTER TABLE "ACHADMIN"."CANI_UNDERLYING" ADD CONSTRAINT "SYS_C0011546" FOREIGN KEY
	("CANC_ASSIGNMENT_ID_UNDRLYG_FK")
	REFERENCES "ACHADMIN"."CANI_ASSIGNMENT"
	("CANC_ASSIGNMENT_ID");
CREATE SEQUENCE  "ACHADMIN"."CANI_UNDERLYING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."CANI_UNDERLYING_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."CANI_UNDERLYING"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
    SELECT CANI_UNDERLYING_SEQ.NEXTVAL INTO :NEW.CANC_UNDRLYG_ID FROM SYS.DUAL;
END;
COMMIT
