--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."DDI_TXN_INFO" (
		"DDI_TXN_INFO_ID" NUMBER NOT NULL,
		"DDI_GP_HDR_ID_TXN_FK" NUMBER,
		"PMT_ID_INSTR_ID" VARCHAR2(35 CHAR),
		"PMT_ID_ENDTOEND_ID" VARCHAR2(30 CHAR),
		"PMT_ID_TXN_ID" VARCHAR2(16 CHAR),
		"INTERBANK_SETTLE_AMNT" NUMBER(18 , 5),
		"STLMT_PRITRY" VARCHAR2(40 CHAR),
		"CHARGE_BEARER" VARCHAR2(10 CHAR) DEFAULT 'SLEV',
		"INSTD_AGT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"INSTD_AGT_FIN_ID_CLR_SYS_MID" VARCHAR2(40 CHAR),
		"INSTD_AGT_BNCHID_ID" VARCHAR2(35 CHAR),
		"DBTR_NAME" VARCHAR2(140 CHAR),
		"DBTR_ID_PRVTID_OTHR_ID" VARCHAR2(35 CHAR),
		"DBTR_ID_PRVTID_OTHR_SCHNM_PRTY" VARCHAR2(35 CHAR),
		"DBTRACCT_ID_IBAN" VARCHAR2(30 CHAR),
		"DBTRACCT_ID_OTHR_ID" VARCHAR2(34 CHAR),
		"DBTRAGNT_ID_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"DBTRAGNT_ID_FIN_ID_CLR_SYS_MID" VARCHAR2(35 CHAR),
		"DBTRAGNT_BNCHID_ID" VARCHAR2(35 CHAR),
		"CDTR_NAME" VARCHAR2(140 CHAR),
		"CDTR_ID_PRVTID_OTHR_ID" VARCHAR2(35 CHAR),
		"CDTR_ID_PRVTID_OTHR_SCHNM_PRTY" VARCHAR2(35 CHAR),
		"CDTRACCT_ID_IBAN" VARCHAR2(30 CHAR),
		"CDTRACCT_ID_OTHR_ID" VARCHAR2(34 CHAR),
		"CGTRAGT_FIN_ID_BICFI" VARCHAR2(40 CHAR),
		"CGTRAGT_FIN_ID_CLR_SYS_MID" VARCHAR2(35 CHAR),
		"CGTRAGT_BNCHID_ID" VARCHAR2(35 CHAR),
		"PURP_PROPTYCHAR" VARCHAR2(35 CHAR),
		"STATUS" VARCHAR2(35 CHAR),
		"CBS_TRAN_REF" VARCHAR2(50 CHAR),
		"DD_TXN_MNDTRLTDINF_MNDTID" VARCHAR2(20 CHAR),
		"DD_TXN_MNDTRLTDINF_FSTCOLNDT" VARCHAR2(35 CHAR),
		"CBS_PAY_REF" VARCHAR2(35 CHAR),
		"EXEC_DESC" VARCHAR2(2000 CHAR),
		"DESCRIPTION" VARCHAR2(2000),
		"MSG_ID" VARCHAR2(20),
		"FAULT_CODE" VARCHAR2(30),
		"FAULT_STRING" VARCHAR2(500),
		"CBS_REQUEST_MESSAGE" CLOB,
		"TXN_ID" VARCHAR2(25 CHAR),
		"CBO_GRP_STATUS" VARCHAR2(40),
		"CBO_TXN_STATUS" VARCHAR2(150)
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."DDI_TXN_INFO" ADD CONSTRAINT "SYS_C0011496" CHECK ("DDI_TXN_INFO_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."DDI_TXN_INFO" ADD CONSTRAINT "SYS_C0011497" PRIMARY KEY
	("DDI_TXN_INFO_ID");

ALTER TABLE "ACHADMIN"."DDI_TXN_INFO" ADD CONSTRAINT "SYS_C0011498" FOREIGN KEY
	("DDI_GP_HDR_ID_TXN_FK")
	REFERENCES "ACHADMIN"."DDI_GP_HEADER_INFO"
	("DDI_GP_HEADER_ID")
	DISABLE;

	CREATE SEQUENCE  "ACHADMIN"."DDI_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."DDI_TXN_INFO_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."DDI_TXN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
   SELECT DDI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.DDI_TXN_INFO_ID FROM SYS.DUAL;
END;

COMMIT

