--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."MANDATE_MGMT_INFO" (
		"MND_GP_HDR_ID" NUMBER NOT NULL,
		"MI_REFERENCE" VARCHAR2(35 CHAR),
		"MND_GP_HDR_CRE_DT_TM" DATE,
		"LCLINSTRMT_CD" VARCHAR2(35 CHAR),
		"RECURRINGFREQUENCY" VARCHAR2(4 CHAR),
		"FREQUENCY" VARCHAR2(4 CHAR),
		"FROMDATE" DATE,
		"TODATE" DATE,
		"COLLECTIONAMT" NUMBER(13 , 5),
		"MAXIMUMAMT" NUMBER(13 , 5),
		"MNDT_REASON" VARCHAR2(35 CHAR),
		"CDTR_NAME" VARCHAR2(140 CHAR),
		"CDTR_IDTYPE" VARCHAR2(35 CHAR),
		"CDTR_ID" VARCHAR2(35 CHAR),
		"CDTR_ACCOUNT" VARCHAR2(34 CHAR),
		"CDTR_BICFI" VARCHAR2(11 CHAR),
		"CDTR_BRNCHID" VARCHAR2(35 CHAR),
		"DBTR_NAME" VARCHAR2(140 CHAR),
		"DBTR_ID" VARCHAR2(35 CHAR),
		"DBTR_IDTYPE" VARCHAR2(35 CHAR),
		"DBTR_ACCOUNT" VARCHAR2(34 CHAR),
		"DBTR_BICFI" VARCHAR2(11 CHAR),
		"DBTR_BRNCHID" VARCHAR2(35 CHAR),
		"RFRDDOC_NB" VARCHAR2(400 CHAR),
		"MI_MA_SPLDT_ENVP_IRREVOCABLE" VARCHAR2(11 CHAR),
		"MI_MA_SPLDT_ENVP_INITBY" VARCHAR2(8 CHAR),
		"MI_MA_SPLDT_ENVP_AUTOPOSTPAY" VARCHAR2(5 CHAR),
		"MI_MA_SPLDT_ENVP_RCURFRQCY" NUMBER(2 , 0),
		"MI_MA_SPLDT_ENVP_PRSNTEACH" VARCHAR2(400 CHAR),
		"MI_MA_SPLDT_ENVP_NMPYMTS" NUMBER(3 , 0),
		"MI_MA_SPLDT_ENVP_TXPURP" VARCHAR2(35 CHAR),
		"MND_SPLDT_ENVP_ATCMT_FNAME" VARCHAR2(255 CHAR),
		"MND_SPLDT_ENVP_ATCMT_FSIZE" NUMBER(19 , 0),
		"MND_SPLDT_ENVP_ATCMT_FDATA" BLOB,
		"MND_SPLDT_ENVP_ATCMT_FTYPE" VARCHAR2(255 CHAR),
		"MND_SPLDT_ENVP_ATCMT_FCMT" VARCHAR2(255 CHAR),
		"MI_STATUS" VARCHAR2(100 CHAR),
		"DESCRIPTION" VARCHAR2(2000),
		"MA_STATUS" VARCHAR2(100 CHAR),
		"MT_STATUS" VARCHAR2(100 CHAR),
		"MA_REFERENCE" VARCHAR2(35),
		"MT_REFERENCE" VARCHAR2(35),
		"MA_REASON" VARCHAR2(40),
		"MT_REASON" VARCHAR2(40),
		"MND_GP_HDP_MSGID" VARCHAR2(40 CHAR),
		"STATUS" VARCHAR2(40)
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."MANDATE_MGMT_INFO" ADD CONSTRAINT "SYS_C0011513" CHECK ("MND_GP_HDR_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."MANDATE_MGMT_INFO" ADD CONSTRAINT "SYS_C0011514" PRIMARY KEY
	("MND_GP_HDR_ID");
CREATE SEQUENCE  "ACHADMIN"."MANDATE_MGMT_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."MANDATE_MGMT_INFO_TRG" 
	BEFORE INSERT ON "ACHADMIN"."MANDATE_MGMT_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  
      SELECT MANDATE_MGMT_INFO_SEQ.NEXTVAL INTO :NEW.MND_GP_HDR_ID FROM SYS.DUAL;
    
END;
COMMIT
