--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ESBACH"."PAYLOAD_LOGGING_TAB" (
		"MESSAGE_ID" VARCHAR2(60),
		"ESB_CBO_REQ_MSG" CLOB,
		"ESB_CBO_RES_MSG" CLOB,
		"FLOW_NAME" VARCHAR2(60),
		"EXCE_DESC" CLOB,
		"ESB_CBO_REQ_TIMESTAMP" TIMESTAMP,
		"ESB_CBO_RES_TIMESTAMP" TIMESTAMP,
		"EXCE_TIMESTAMP" TIMESTAMP,
		"EXCE_ORG_MSG" CLOB
	)
	LOGGING;

