--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."PRI_GP_HEADER_INFO" (
		"PR_GP_HEADER_ID" NUMBER NOT NULL,
		"MSG_ID" VARCHAR2(16 CHAR),
		"CRE_DT_TM" VARCHAR2(40),
		"NB_OF_TXS" NUMBER,
		"TTL_RTRD_INTR_BK_STTLM_AMT" NUMBER(18 , 5),
		"INTR_BK_STTLM_DT" DATE,
		"STTLM_INF_STTLMN_MTD" VARCHAR2(35 CHAR) DEFAULT 'CLRG' NOT NULL,
		"STTLM_INF_CLR_SYS_PRTRY" VARCHAR2(35 CHAR) DEFAULT 'CBO' NOT NULL,
		"INSTG_AGT_FIN_INSTN_ID_BICFI" VARCHAR2(35 CHAR),
		"INSTG_AGT_BRNCH_ID_ID" VARCHAR2(35 CHAR),
		"INSTD_AGT_FIN_INSTN_ID_BICFI" VARCHAR2(35 CHAR),
		"INSTD_AGT_BRNCH_ID_ID" VARCHAR2(35 CHAR),
		"SOURCE_SYS_CODE" VARCHAR2(35 CHAR),
		"SOURCE_SYS_ID" VARCHAR2(35 CHAR),
		"GROUPRTR_STATUS" VARCHAR2(20 CHAR),
		"SRC_MSG" CLOB
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."PRI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011507" CHECK ("PR_GP_HEADER_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."PRI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011508" CHECK ("STTLM_INF_STTLMN_MTD" IS NOT NULL);

ALTER TABLE "ACHADMIN"."PRI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011509" CHECK ("STTLM_INF_CLR_SYS_PRTRY" IS NOT NULL);

ALTER TABLE "ACHADMIN"."PRI_GP_HEADER_INFO" ADD CONSTRAINT "SYS_C0011510" PRIMARY KEY
	("PR_GP_HEADER_ID");
CREATE SEQUENCE  "ACHADMIN"."PRI_GP_HEADER_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."PRI_GP_HEADER_INFO_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."PRI_GP_HEADER_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   
      SELECT PRI_GP_HEADER_INFO_SEQ.NEXTVAL INTO :NEW.PR_GP_HEADER_ID FROM SYS.DUAL;
    
END;

COMMIT