--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."REVI_TXN_INFO" (
		"REV_TXN_INF_ID" NUMBER NOT NULL,
		"REV_GRP_HDR_ID_TXN_INFO_FK" NUMBER,
		"RVSL_ID" VARCHAR2(16 CHAR),
		"ORGNL_TX_ID" VARCHAR2(16 CHAR),
		"RVSD_INTRBK_STTLM_AMT" NUMBER(18 , 5),
		"STATUS" VARCHAR2(40 CHAR),
		"CBS_TRAN_REF" VARCHAR2(25 CHAR),
		"ACCOUNT" VARCHAR2(30 CHAR),
		"EXEC_DESC" VARCHAR2(2000 CHAR),
		"CBS_PAY_REF" VARCHAR2(35 CHAR),
		"DESCRIPTION" VARCHAR2(2000),
		"MSG_ID" VARCHAR2(40),
		"CBS_REQUEST_MESSAGE" CLOB,
		"FAULT_CODE" VARCHAR2(20),
		"FAULT_STRING" VARCHAR2(500),
		"TXN_FOUND" VARCHAR2(20),
		"TXN_ID" VARCHAR2(25 CHAR),
		"CBO_GRP_STATUS" VARCHAR2(40),
		"CBO_TXN_STATUS" VARCHAR2(150)
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."REVI_TXN_INFO" ADD CONSTRAINT "SYS_C0011521" CHECK ("REV_TXN_INF_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."REVI_TXN_INFO" ADD CONSTRAINT "SYS_C0011522" PRIMARY KEY
	("REV_TXN_INF_ID");

ALTER TABLE "ACHADMIN"."REVI_TXN_INFO" ADD CONSTRAINT "SYS_C0011523" FOREIGN KEY
	("REV_GRP_HDR_ID_TXN_INFO_FK")
	REFERENCES "ACHADMIN"."REVI_GRP_HEADER_INFO"
	("REV_GRP_HEADER_ID");
CREATE SEQUENCE  "ACHADMIN"."REVI_TXN_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."REVI_TXN_INFO_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."REVI_TXN_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
    
    SELECT REVI_TXN_INFO_SEQ.NEXTVAL INTO :NEW.REV_TXN_INF_ID FROM SYS.DUAL;
END;

COMMIT
