--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."WPS_SIF_RECORD_INFO" (
		"WPS_SIF_RECORD_INFO_ID" NUMBER NOT NULL,
		"SIF_FILE_NAME" VARCHAR2(200 CHAR) NOT NULL,
		"EMPLOYEE_ID_TYPE" VARCHAR2(20 CHAR),
		"EMPLOYEE_ID" VARCHAR2(20 CHAR),
		"EMPLOYEE_NAME" VARCHAR2(70 CHAR),
		"EMPLOYEE_BANK_CODE" VARCHAR2(10 CHAR),
		"EMPLOYEE_ACC_NO" VARCHAR2(30 CHAR),
		"SALARY_FREQUENCY" VARCHAR2(1 CHAR),
		"NO_OF_WORKING_DAYS" VARCHAR2(10 CHAR),
		"NET_SALARY" VARCHAR2(30 CHAR),
		"BASIC_SALARY" VARCHAR2(30 CHAR),
		"EXTRA_HOURS" VARCHAR2(10 CHAR),
		"EXTRA_INCOME" VARCHAR2(30 CHAR),
		"DEDUCTIONS" VARCHAR2(30 CHAR),
		"SOCIAL_SECURITY_DEDUCTIONS" VARCHAR2(30 CHAR),
		"NOTES_COMMENTS" VARCHAR2(300 CHAR),
		"RECORD_ID" VARCHAR2(400 CHAR),
		"DUPLICATE" VARCHAR2(20 CHAR),
		"STATUS" VARCHAR2(100 CHAR),
		"EXEC_DESC" VARCHAR2(4000 CHAR),
		"TXN_REF_ID" VARCHAR2(30 CHAR),
		"WPS_SIF_HEADER_INFO_ID" NUMBER NOT NULL,
		"ACCOUNT_STATUS" VARCHAR2(20 CHAR),
		"CBS_PAY_REF" VARCHAR2(50),
		"REFERENCE_NUMBER" VARCHAR2(35 CHAR),
		"CBS_FAULT_CODE" VARCHAR2(40),
		"CBS_FAULT_STRING" VARCHAR2(100),
		"CHL_REFERENCE" VARCHAR2(30),
		"CBS_REQUEST_MESSAGE" CLOB
	)
	LOGGING;

ALTER TABLE "ACHADMIN"."WPS_SIF_RECORD_INFO" ADD CONSTRAINT "SYS_C0011533" CHECK ("WPS_SIF_RECORD_INFO_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."WPS_SIF_RECORD_INFO" ADD CONSTRAINT "SYS_C0011534" CHECK ("SIF_FILE_NAME" IS NOT NULL);

ALTER TABLE "ACHADMIN"."WPS_SIF_RECORD_INFO" ADD CONSTRAINT "SYS_C0011535" CHECK ("WPS_SIF_HEADER_INFO_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."WPS_SIF_RECORD_INFO" ADD CONSTRAINT "SYS_C0011536" PRIMARY KEY
	("WPS_SIF_RECORD_INFO_ID");

ALTER TABLE "ACHADMIN"."WPS_SIF_RECORD_INFO" ADD CONSTRAINT "SYS_C0011537" FOREIGN KEY
	("WPS_SIF_HEADER_INFO_ID")
	REFERENCES "ACHADMIN"."WPS_SIF_HEADER_INFO"
	("WPS_SIF_HEADER_INFO_ID");
CREATE SEQUENCE  "ACHADMIN"."WPS_SIF_RECORD_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."WPS_SIF_RECORD_INFO_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."WPS_SIF_RECORD_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   SELECT WPS_SIF_RECORD_INFO_SEQ.NEXTVAL INTO :NEW.WPS_SIF_RECORD_INFO_ID FROM SYS.DUAL;
END;

