--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "ACHADMIN"."WPS_ADD_OPS_INFO" (
		"WPS_ADD_OPS_INFO_ID" NUMBER NOT NULL,
		"ADDOPS_FILE_NAME" VARCHAR2(50 CHAR),
		"EMPLOYER_NUM_TYPE" VARCHAR2(3 CHAR),
		"EMPLOYER_CR_NO" VARCHAR2(20 CHAR),
		"PAYER_NUMBER_TYPE" VARCHAR2(3 CHAR),
		"PAYER_CR_NO" VARCHAR2(20 CHAR),
		"EMPLOYER_NAME" VARCHAR2(70 CHAR),
		"PAYER_NAME" VARCHAR2(70 CHAR),
		"PAYER_ACCTNO_IBAN" VARCHAR2(30 CHAR),
		"PAYER_BNK_SHORT_NAME" VARCHAR2(4 CHAR),
		"PAYER_BRANCH" VARCHAR2(12 CHAR),
		"EMPLOYER_TYPE" VARCHAR2(7 CHAR),
		"EMPLOYER_BIZ_TYPE" VARCHAR2(70 CHAR),
		"EMPLOYER_BRANCHES_COUNT" VARCHAR2(3 CHAR),
		"EMPLOYER_GRADE" VARCHAR2(1 CHAR),
		"EMPLOYER_EMAIL" VARCHAR2(254 CHAR),
		"EMPLOYER_ADDRESS" VARCHAR2(254 CHAR),
		"EMPLOYER_PH_NO" VARCHAR2(20 CHAR),
		"EMPLOYER_POSTAL_CODE" VARCHAR2(14 CHAR),
		"EMPLOYER_POBOX" VARCHAR2(6 CHAR),
		"EMPLOYER_SIGNATORY1" VARCHAR2(70 CHAR),
		"EMPLOYER_SIGNATORY2" VARCHAR2(70 CHAR),
		"EMPLOYER_SIGNATORY3" VARCHAR2(70 CHAR),
		"STATUS_CODE" VARCHAR2(20 CHAR),
		"EXEC_DESC" VARCHAR2(2000 CHAR),
		"STATUS_TRAIL" VARCHAR2(40 CHAR),
		"FAILED_RECORD_NO" NUMBER(3 , 0)
	)
	LOGGING;

CREATE UNIQUE INDEX "ACHADMIN"."WPS_ADD_OPS_INFO_UK1"
	ON "ACHADMIN"."WPS_ADD_OPS_INFO"
	("ADDOPS_FILE_NAME"		ASC)
	LOGGING;

ALTER TABLE "ACHADMIN"."WPS_ADD_OPS_INFO" ADD CONSTRAINT "SYS_C0011528" CHECK ("WPS_ADD_OPS_INFO_ID" IS NOT NULL);

ALTER TABLE "ACHADMIN"."WPS_ADD_OPS_INFO" ADD CONSTRAINT "SYS_C0011529" PRIMARY KEY
	("WPS_ADD_OPS_INFO_ID");

ALTER TABLE "ACHADMIN"."WPS_ADD_OPS_INFO" ADD CONSTRAINT "WPS_ADD_OPS_INFO_UK1" UNIQUE
	("ADDOPS_FILE_NAME");
CREATE SEQUENCE  "ACHADMIN"."WPS_ADD_OPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER "ACHADMIN"."WPS_ADD_OPS_INFO_TRIG" 
	BEFORE INSERT ON "ACHADMIN"."WPS_ADD_OPS_INFO"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
   SELECT WPS_ADD_OPS_SEQ.NEXTVAL INTO :NEW.WPS_ADD_OPS_INFO_ID FROM SYS.DUAL;
END;
COMMIT
